/***************************************************************************//**
* @file
* Interface Library Shared
*
* @version @n 1.0
* @date @n 1/26/2014
*
* @author @n Kwabena W. Agyeman
* @copyright @n (c) 2014 Kwabena W. Agyeman
* @n All rights reserved - Please see the end of the file for the terms of use
*
* @par Update History:
* @n v1.0 - Original release - 1/26/2014
*******************************************************************************/

#ifndef ILSHARED_H
#define ILSHARED_H

/*******************************************************************************
* Serial Protocol (Little Endian):
*
*   Layer 0:
*
*       Unsigned Char: CC_ESCAPE (unreserved)
*       Unsigned Char: CC_NULL (reserved)
*       Unsigned Char: PacketSize [0:250]
*       Unsigned Char: ~PacketSize ~[0:250]
*
*       ... <Layer 1 Packet Data> ...
*
*       Unsigned Word: CRC-16-CCITT
*
*   Layer 1:
*
*       Unsigned Word: SerialFunction
*       Unsigned Word: PacketSize [0:65532]
*
*       ... <Function Handle(s)> ...
*       ... <Function Argument(s)> ...
*
* Baud Rate:
*
*   DTE:
*
*       Default to 2,400 BPS (8N1)
*
*           Min = 2,400 BPS (8N1)
*           Max = 3,000,000 BPS (8N1)
*
*   DCE:
*
*       Default to 2,400 BPS (8N1)
*
*           Min = 2,400 BPS (8N1)
*           Max = 3,000,000 BPS (8N1)
*
* Flow Control:
*
*   DTE:
*
*       Default to 16 Credits - Window Size = 4,096 Bytes ((4 + 250 + 2) * 16)
*
*           On receipt of CC_XON: Increment 'credits' by 1 (max 16)
*           On receipt of CC_XOFF: Increment 'credits' by 1 (max 16)
*
*       Only transmit a queued packet if 'credits' > 0
*       Decrement 'credits' by 1 on transmit of a queued packet
*       Transmit CC_XON(ACK)/CC_XOFF(NAK) to the DCE on receipt of a packet
*
*   DCE:
*
*       Default to 16 Credits - Window Size = 4,096 Bytes ((4 + 250 + 2) * 16)
*
*           On receipt of CC_XON: Increment 'credits' by 1 (max 16)
*           On receipt of CC_XOFF: Increment 'credits' by 1 (max 16)
*
*       Only transmit a queued packet if 'credits' > 0
*       Decrement 'credits' by 1 on transmit of a queued packet
*       Transmit CC_XON(ACK)/CC_XOFF(NAK) to the DTE on receipt of a packet
*
* Line Break:
*
*   DTE:
*
*       1. On reset send (!DTR and !RTS) for 100 ms to reset the DCE state
*       2. Wait 100 ms then clear receive queue
*
*   DCE:
*
*       1. On reset send (!TX or !CTS) for 100 ms to reset the DTE state
*       2. Wait 100 ms then clear receive queue
*
*******************************************************************************/

#define DEF_CREDITS 16
#define MAX_CREDITS 16

#define LAYER_0_HEAD_SIZE 4
#define LAYER_0_TAIL_SIZE 2
#define MAX_LAYER_0_DATA_SIZE (256 - LAYER_0_HEAD_SIZE - LAYER_0_TAIL_SIZE)

#define LAYER_1_HEAD_SIZE 4
#define LAYER_1_TAIL_SIZE 0
#define MAX_LAYER_1_DATA_SIZE (65536 - LAYER_1_HEAD_SIZE - LAYER_1_TAIL_SIZE)

#define MIN_BAUD_RATE 2400
#define DEF_BAUD_RATE 2400
#define MAX_BAUD_RATE 3000000
#define MID_SLOW_BAUD_RATE 19200
#define MID_FAST_BAUD_RATE 115200

#define DCE_MAX_QUEUE_DEPTH 16
#define DTE_MAX_QUEUE_DEPTH 64

#define BASE_SIZE 64

enum SerialBase
{
    ESCAPE_BASE,
    ESCAPE_FILE_BASE,
    ESCAPE_FOLDER_BASE,
    ESCAPE_INPUT_DIALOG_BASE,
    ESCAPE_OUTPUT_DIALOG_BASE,
    ESCAPE_BASE_SPACER_0, // spacer
    ESCAPE_BASE_SPACER_1, // spacer
    ESCAPE_BASE_SPACER_2, // spacer
    ESCAPE_BASE_SPACER_3, // spacer

    WINDOW_BASE,

    TERMINAL_BASE,

    OSCILLOSCOPE_BASE,
    OSCILLOSCOPE_XAXIS_BASE,
    OSCILLOSCOPE_YAXIS_BASE,
    OSCILLOSCOPE_FFTXAXIS_BASE,
    OSCILLOSCOPE_FFTYAXIS_BASE,
    OSCILLOSCOPE_BAR_BASE,
    OSCILLOSCOPE_BAR_BASE_EXTENSION,
    OSCILLOSCOPE_CURVE_BASE,
    OSCILLOSCOPE_CURVE_BASE_EXTENSION,
    OSCILLOSCOPE_GRAPH_BASE,
    OSCILLOSCOPE_GRAPH_BASE_EXTENSION,
    OSCILLOSCOPE_BOX_BASE,
    OSCILLOSCOPE_BOX_BASE_EXTNESION,
    OSCILLOSCOPE_BASE_SPACER_0, // spacer
    OSCILLOSCOPE_BASE_SPACER_1, // spacer
    OSCILLOSCOPE_BASE_SPACER_2, // spacer
    OSCILLOSCOPE_BASE_SPACER_3, // spacer

    TABLE_BASE,
    TABLE_ROW_BASE,
    TABLE_COLUMN_BASE,

    TREE_BASE,

    GRAPHICS_BASE,
    GRAPHICS_BASE_EXTENSION_0,
    GRAPHICS_BASE_EXTENSION_1,
    GRAPHICS_BASE_SPACER_0, // spacer
    GRAPHICS_BASE_SPACER_1, // spacer
    GRAPHICS_BASE_SPACER_2, // spacer
    GRAPHICS_BASE_SPACER_3, // spacer

    INTERFACE_BASE,
    INTERFACE_GROUP_BOX_BASE,
    INTERFACE_PUSH_BUTTON_BASE,
    INTERFACE_RADIO_BUTTON_BASE,
    INTERFACE_CHECK_BOX_BASE,
    INTERFACE_LINE_EDIT_BASE,
    INTERFACE_INT_SPIN_BOX_BASE,
    INTERFACE_BIN_SPIN_BOX_BASE,
    INTERFACE_HEX_SPIN_BOX_BASE,
    INTERFACE_DOUBLE_SPIN_BOX_BASE,
    INTERFACE_TIME_EDIT_BASE,
    INTERFACE_DATE_EDIT_BASE,
    INTERFACE_DATE_TIME_EDIT_BASE,
    INTERFACE_SLIDER_BASE,
    INTERFACE_LABEL_BASE,
    INTERFACE_PROGRESS_BAR_BASE,
    INTERFACE_SEPERATOR_BASE,
    INTERFACE_BASE_SPACER_0, // spacer
    INTERFACE_BASE_SPACER_1, // spacer
    INTERFACE_BASE_SPACER_2, // spacer
    INTERFACE_BASE_SPACER_3 // spacer
};

enum SerialFunction
{
    // Serial Escape

    ESCAPE_NAK =
    (ESCAPE_BASE * BASE_SIZE),
    ESCAPE_NAK_SPACER, // spacer
    ESCAPE_ACK,
    ESCAPE_ACK_SPACER, // spacer
    ESCAPE_RESET_DCE,
    ESCAPE_RESET_DCE_SPACER, // spacer
    ESCAPE_RESET_DTE,
    ESCAPE_RESET_DTE_SPACER, // spacer
    ESCAPE_GET_VERSION_INT,
    ESCAPE_GET_VERSION_INT_SPACER, // spacer
    ESCAPE_GET_VERSION_STR,
    ESCAPE_GET_VERSION_STR_SPACER, // spacer
    ESCAPE_OPEN_PROCESS,
    ESCAPE_OPEN_PROCESS_SPACER, // spacer
    ESCAPE_OPEN_URL,
    ESCAPE_OPEN_URL_SPACER, // spacer
    ESCAPE_SPACER_00, // spacer
    ESCAPE_SPACER_01, // spacer
    ESCAPE_SPACER_02, // spacer
    ESCAPE_SPACER_03, // spacer
    ESCAPE_SPACER_04, // spacer
    ESCAPE_SPACER_05, // spacer
    ESCAPE_SPACER_06, // spacer
    ESCAPE_SPACER_07, // spacer
    ESCAPE_SPACER_08, // spacer
    ESCAPE_SPACER_09, // spacer
    ESCAPE_SPACER_10, // spacer
    ESCAPE_SPACER_11, // spacer
    ESCAPE_SPACER_12, // spacer
    ESCAPE_SPACER_13, // spacer
    ESCAPE_SPACER_14, // spacer
    ESCAPE_SPACER_15, // spacer
    ESCAPE_SET_CHECKSUM_MODE,
    ESCAPE_GET_CHECKSUM_MODE,
    ESCAPE_SET_MAX_CREDITS,
    ESCAPE_GET_MAX_CREDITS,
    ESCAPE_SET_MAX_LAYER_0_DATA_SIZE,
    ESCAPE_GET_MAX_LAYER_0_DATA_SIZE,
    ESCAPE_SET_BAUD_RATE,
    ESCAPE_GET_BAUD_RATE,

    ESCAPE_INPUT_DIALOG_SPACER_0 = // spacer
    (ESCAPE_INPUT_DIALOG_BASE * BASE_SIZE),
    ESCAPE_INPUT_DIALOG_SPACER_1, // spacer
    ESCAPE_INPUT_DIALOG_SPACER_2, // spacer
    ESCAPE_INPUT_DIALOG_SPACER_3, // spacer
    ESCAPE_SHOW_COLOR_DIALOG,
    ESCAPE_SHOW_COLOR_DIALOG_ON_WINDOW,
    ESCAPE_SHOW_COLOR_DIALOG_SPACER_0, // spacer
    ESCAPE_SHOW_COLOR_DIALOG_SPACER_1, // spacer
    ESCAPE_SHOW_FOLDER_DIALOG,
    ESCAPE_SHOW_FOLDER_DIALOG_ON_WINDOW,
    ESCAPE_SHOW_FOLDER_DIALOG_SPACER_0, // spacer
    ESCAPE_SHOW_FOLDER_DIALOG_SPACER_1, // spacer
    ESCAPE_SHOW_OPEN_FILE_DIALOG,
    ESCAPE_SHOW_OPEN_FILE_DIALOG_ON_WINDOW,
    ESCAPE_SHOW_OPEN_FILE_DIALOG_SPACER_0, // spacer
    ESCAPE_SHOW_OPEN_FILE_DIALOG_SPACER_1, // spacer
    ESCAPE_SHOW_SAVE_FILE_DIALOG,
    ESCAPE_SHOW_SAVE_FILE_DIALOG_ON_WINDOW,
    ESCAPE_SHOW_SAVE_FILE_DIALOG_SPACER_0, // spacer
    ESCAPE_SHOW_SAVE_FILE_DIALOG_SPACER_1, // spacer
    ESCAPE_SHOW_FONT_DIALOG,
    ESCAPE_SHOW_FONT_DIALOG_ON_WINDOW,
    ESCAPE_SHOW_FONT_DIALOG_SPACER_0, // spacer
    ESCAPE_SHOW_FONT_DIALOG_SPACER_1, // spacer
    ESCAPE_SHOW_DOUBLE_DIALOG,
    ESCAPE_SHOW_DOUBLE_DIALOG_ON_WINDOW,
    ESCAPE_SHOW_DOUBLE_DIALOG_SPACER_0, // spacer
    ESCAPE_SHOW_DOUBLE_DIALOG_SPACER_1, // spacer
    ESCAPE_SHOW_INT_DIALOG,
    ESCAPE_SHOW_INT_DIALOG_ON_WINDOW,
    ESCAPE_SHOW_INT_DIALOG_SPACER_0, // spacer
    ESCAPE_SHOW_INT_DIALOG_SPACER_1, // spacer
    ESCAPE_SHOW_TEXT_DIALOG,
    ESCAPE_SHOW_TEXT_DIALOG_ON_WINDOW,
    ESCAPE_SHOW_TEXT_DIALOG_SPACER_0, // spacer
    ESCAPE_SHOW_TEXT_DIALOG_SPACER_1, // spacer

    ESCAPE_OUTPUT_DIALOG_SPACER_0 = // spacer
    (ESCAPE_OUTPUT_DIALOG_BASE * BASE_SIZE),
    ESCAPE_OUTPUT_DIALOG_SPACER_1, // spacer
    ESCAPE_OUTPUT_DIALOG_SPACER_2, // spacer
    ESCAPE_OUTPUT_DIALOG_SPACER_3, // spacer
    ESCAPE_SHOW_CRITICAL_DIALOG,
    ESCAPE_SHOW_CRITICAL_DIALOG_ON_WINDOW,
    ESCAPE_SHOW_CRITICAL_DIALOG_SPACER_0, // spacer
    ESCAPE_SHOW_CRITICAL_DIALOG_SPACER_1, // spacer
    ESCAPE_SHOW_INFORMATION_DIALOG,
    ESCAPE_SHOW_INFORMATION_DIALOG_ON_WINDOW,
    ESCAPE_SHOW_INFORMATION_DIALOG_SPACER_0, // spacer
    ESCAPE_SHOW_INFORMATION_DIALOG_SPACER_1, // spacer
    ESCAPE_SHOW_QUESTION_DIALOG,
    ESCAPE_SHOW_QUESTION_DIALOG_ON_WINDOW,
    ESCAPE_SHOW_QUESTION_DIALOG_SPACER_0, // spacer
    ESCAPE_SHOW_QUESTION_DIALOG_SPACER_1, // spacer
    ESCAPE_SHOW_WARNING_DIALOG,
    ESCAPE_SHOW_WARNING_DIALOG_ON_WINDOW,
    ESCAPE_SHOW_WARNING_DIALOG_SPACER_0, // spacer
    ESCAPE_SHOW_WARNING_DIALOG_SPACER_1, // spacer

    // Serial Window

    WINDOW_CLOSE_WINDOW =
    (WINDOW_BASE * BASE_SIZE),
    WINDOW_CLOSE_WINDOWS,
    WINDOW_CLOSE_WINDOW_SPACER_0, // spacer
    WINDOW_CLOSE_WINDOW_SPACER_1, // spacer
    WINDOW_CLOSE_WINDOW_SPACER_2, // spacer
    WINDOW_CLOSE_WINDOW_SPACER_3, // spacer
    WINDOW_CLOSE_WINDOW_SPACER_4, // spacer
    WINDOW_CLOSE_WINDOW_SPACER_5, // spacer
    WINDOW_DELETE_WINDOW,
    WINDOW_DELETE_WINDOWS,
    WINDOW_DELETE_WINDOW_SPACER_0, // spacer
    WINDOW_DELETE_WINDOW_SPACER_1, // spacer
    WINDOW_DELETE_WINDOW_SPACER_2, // spacer
    WINDOW_DELETE_WINDOW_SPACER_3, // spacer
    WINDOW_DELETE_WINDOW_SPACER_4, // spacer
    WINDOW_DELETE_WINDOW_SPACER_5, // spacer
    WINDOW_SET_WINDOW_TITLE,
    WINDOW_GET_WINDOW_TITLE,
    WINDOW_SET_WINDOW_MESSAGE,
    WINDOW_GET_WINDOW_MESSAGE,
    WINDOW_SET_WINDOW_VISIBLE,
    WINDOW_GET_WINDOW_VISIBLE,
    WINDOW_SET_WINDOW_MINIMIZED,
    WINDOW_GET_WINDOW_MINIMIZED,
    WINDOW_SET_WINDOW_MAXIMIZED,
    WINDOW_GET_WINDOW_MAXIMIZED,
    WINDOW_SET_WINDOW_FULL_SCREEN,
    WINDOW_GET_WINDOW_FULL_SCREEN,

    // Serial Terminal

    TERMINAL_NEW_UNDOCKED_WINDOW =
    (TERMINAL_BASE * BASE_SIZE),
    TERMINAL_NEW_UNDOCKED_WINDOW_SPACER_0, // spacer
    TERMINAL_NEW_UNDOCKED_WINDOW_SPACER_1, // spacer
    TERMINAL_NEW_UNDOCKED_WINDOW_SPACER_2, // spacer
    TERMINAL_NEW_DOCKED_WINDOW,
    TERMINAL_NEW_DOCKED_WINDOW_SPACER_0, // spacer
    TERMINAL_NEW_DOCKED_WINDOW_SPACER_1, // spacer
    TERMINAL_NEW_DOCKED_WINDOW_SPACER_2, // spacer
    TERMINAL_NEW_MAIN_DOCKED_WINDOW,
    TERMINAL_NEW_MAIN_DOCKED_WINDOW_SPACER_0, // spacer
    TERMINAL_NEW_MAIN_DOCKED_WINDOW_SPACER_1, // spacer
    TERMINAL_NEW_MAIN_DOCKED_WINDOW_SPACER_2, // spacer
    TERMINAL_PRINT,
    TERMINAL_PRINTLN,

    // Serial Oscilloscope

    OSCILLOSCOPE_NEW_UNDOCKED_WINDOW =
    (OSCILLOSCOPE_BASE * BASE_SIZE),
    OSCILLOSCOPE_NEW_UNDOCKED_WINDOW_SPACER_0, // spacer
    OSCILLOSCOPE_NEW_UNDOCKED_WINDOW_SPACER_1, // spacer
    OSCILLOSCOPE_NEW_UNDOCKED_WINDOW_SPACER_2, // spacer
    OSCILLOSCOPE_NEW_DOCKED_WINDOW,
    OSCILLOSCOPE_NEW_DOCKED_WINDOW_SPACER_0, // spacer
    OSCILLOSCOPE_NEW_DOCKED_WINDOW_SPACER_1, // spacer
    OSCILLOSCOPE_NEW_DOCKED_WINDOW_SPACER_2, // spacer
    OSCILLOSCOPE_NEW_MAIN_DOCKED_WINDOW,
    OSCILLOSCOPE_NEW_MAIN_DOCKED_WINDOW_SPACER_0, // spacer
    OSCILLOSCOPE_NEW_MAIN_DOCKED_WINDOW_SPACER_1, // spacer
    OSCILLOSCOPE_NEW_MAIN_DOCKED_WINDOW_SPACER_2, // spacer
    OSCILLOSCOPE_REMOVE_DATA,
    OSCILLOSCOPE_REMOVE_DATAS,
    OSCILLOSCOPE_REMOVE_DATA_SPACER_0, // spacer
    OSCILLOSCOPE_REMOVE_DATA_SPACER_1, // spacer
    OSCILLOSCOPE_REMOVE_DATA_SPACER_2, // spacer
    OSCILLOSCOPE_REMOVE_DATA_SPACER_3, // spacer
    OSCILLOSCOPE_REMOVE_DATA_SPACER_4, // spacer
    OSCILLOSCOPE_REMOVE_DATA_SPACER_5, // spacer
    OSCILLOSCOPE_DELETE_PLOT,
    OSCILLOSCOPE_DELETE_PLOTS,
    OSCILLOSCOPE_DELETE_PLOT_SPACER_0, // spacer
    OSCILLOSCOPE_DELETE_PLOT_SPACER_1, // spacer
    OSCILLOSCOPE_DELETE_PLOT_SPACER_2, // spacer
    OSCILLOSCOPE_DELETE_PLOT_SPACER_3, // spacer
    OSCILLOSCOPE_DELETE_PLOT_SPACER_4, // spacer
    OSCILLOSCOPE_DELETE_PLOT_SPACER_5, // spacer
    OSCILLOSCOPE_SET_BACKGROUND_COLOR,
    OSCILLOSCOPE_GET_BACKGROUND_COLOR,

    OSCILLOSCOPE_SET_XAXIS_SCALE_TYPE =
    (OSCILLOSCOPE_XAXIS_BASE * BASE_SIZE),
    OSCILLOSCOPE_GET_XAXIS_SCALE_TYPE,
    OSCILLOSCOPE_SET_XAXIS_SCALE_LOG_BASE,
    OSCILLOSCOPE_GET_XAXIS_SCALE_LOG_BASE,
    OSCILLOSCOPE_SET_XAXIS_SCALE_LOG_BASE_F,
    OSCILLOSCOPE_GET_XAXIS_SCALE_LOG_BASE_F,
    OSCILLOSCOPE_SET_XAXIS_RANGE_AUTO_SCALE,
    OSCILLOSCOPE_GET_XAXIS_RANGE_AUTO_SCALE,
    OSCILLOSCOPE_SET_XAXIS_RANGE_LOWER,
    OSCILLOSCOPE_GET_XAXIS_RANGE_LOWER,
    OSCILLOSCOPE_SET_XAXIS_RANGE_LOWER_F,
    OSCILLOSCOPE_GET_XAXIS_RANGE_LOWER_F,
    OSCILLOSCOPE_SET_XAXIS_RANGE_UPPER,
    OSCILLOSCOPE_GET_XAXIS_RANGE_UPPER,
    OSCILLOSCOPE_SET_XAXIS_RANGE_UPPER_F,
    OSCILLOSCOPE_GET_XAXIS_RANGE_UPPER_F,
    OSCILLOSCOPE_SET_XAXIS_RANGE_REVERSED,
    OSCILLOSCOPE_GET_XAXIS_RANGE_REVERSED,
    OSCILLOSCOPE_SET_XAXIS_LABEL,
    OSCILLOSCOPE_GET_XAXIS_LABEL,

    OSCILLOSCOPE_SET_YAXIS_SCALE_TYPE =
    (OSCILLOSCOPE_YAXIS_BASE * BASE_SIZE),
    OSCILLOSCOPE_GET_YAXIS_SCALE_TYPE,
    OSCILLOSCOPE_SET_YAXIS_SCALE_LOG_BASE,
    OSCILLOSCOPE_GET_YAXIS_SCALE_LOG_BASE,
    OSCILLOSCOPE_SET_YAXIS_SCALE_LOG_BASE_F,
    OSCILLOSCOPE_GET_YAXIS_SCALE_LOG_BASE_F,
    OSCILLOSCOPE_SET_YAXIS_RANGE_AUTO_SCALE,
    OSCILLOSCOPE_GET_YAXIS_RANGE_AUTO_SCALE,
    OSCILLOSCOPE_SET_YAXIS_RANGE_LOWER,
    OSCILLOSCOPE_GET_YAXIS_RANGE_LOWER,
    OSCILLOSCOPE_SET_YAXIS_RANGE_LOWER_F,
    OSCILLOSCOPE_GET_YAXIS_RANGE_LOWER_F,
    OSCILLOSCOPE_SET_YAXIS_RANGE_UPPER,
    OSCILLOSCOPE_GET_YAXIS_RANGE_UPPER,
    OSCILLOSCOPE_SET_YAXIS_RANGE_UPPER_F,
    OSCILLOSCOPE_GET_YAXIS_RANGE_UPPER_F,
    OSCILLOSCOPE_SET_YAXIS_RANGE_REVERSED,
    OSCILLOSCOPE_GET_YAXIS_RANGE_REVERSED,
    OSCILLOSCOPE_SET_YAXIS_LABEL,
    OSCILLOSCOPE_GET_YAXIS_LABEL,

    OSCILLOSCOPE_SET_FFTXAXIS_SCALE_TYPE =
    (OSCILLOSCOPE_FFTXAXIS_BASE * BASE_SIZE),
    OSCILLOSCOPE_GET_FFTXAXIS_SCALE_TYPE,
    OSCILLOSCOPE_SET_FFTXAXIS_SCALE_LOG_BASE,
    OSCILLOSCOPE_GET_FFTXAXIS_SCALE_LOG_BASE,
    OSCILLOSCOPE_SET_FFTXAXIS_SCALE_LOG_BASE_F,
    OSCILLOSCOPE_GET_FFTXAXIS_SCALE_LOG_BASE_F,
    OSCILLOSCOPE_SET_FFTXAXIS_RANGE_AUTO_SCALE,
    OSCILLOSCOPE_GET_FFTXAXIS_RANGE_AUTO_SCALE,
    OSCILLOSCOPE_SET_FFTXAXIS_RANGE_LOWER,
    OSCILLOSCOPE_GET_FFTXAXIS_RANGE_LOWER,
    OSCILLOSCOPE_SET_FFTXAXIS_RANGE_LOWER_F,
    OSCILLOSCOPE_GET_FFTXAXIS_RANGE_LOWER_F,
    OSCILLOSCOPE_SET_FFTXAXIS_RANGE_UPPER,
    OSCILLOSCOPE_GET_FFTXAXIS_RANGE_UPPER,
    OSCILLOSCOPE_SET_FFTXAXIS_RANGE_UPPER_F,
    OSCILLOSCOPE_GET_FFTXAXIS_RANGE_UPPER_F,
    OSCILLOSCOPE_SET_FFTXAXIS_RANGE_REVERSED,
    OSCILLOSCOPE_GET_FFTXAXIS_RANGE_REVERSED,
    OSCILLOSCOPE_SET_FFTXAXIS_LABEL,
    OSCILLOSCOPE_GET_FFTXAXIS_LABEL,

    OSCILLOSCOPE_SET_FFTYAXIS_SCALE_TYPE =
    (OSCILLOSCOPE_FFTYAXIS_BASE * BASE_SIZE),
    OSCILLOSCOPE_GET_FFTYAXIS_SCALE_TYPE,
    OSCILLOSCOPE_SET_FFTYAXIS_SCALE_LOG_BASE,
    OSCILLOSCOPE_GET_FFTYAXIS_SCALE_LOG_BASE,
    OSCILLOSCOPE_SET_FFTYAXIS_SCALE_LOG_BASE_F,
    OSCILLOSCOPE_GET_FFTYAXIS_SCALE_LOG_BASE_F,
    OSCILLOSCOPE_SET_FFTYAXIS_RANGE_AUTO_SCALE,
    OSCILLOSCOPE_GET_FFTYAXIS_RANGE_AUTO_SCALE,
    OSCILLOSCOPE_SET_FFTYAXIS_RANGE_LOWER,
    OSCILLOSCOPE_GET_FFTYAXIS_RANGE_LOWER,
    OSCILLOSCOPE_SET_FFTYAXIS_RANGE_LOWER_F,
    OSCILLOSCOPE_GET_FFTYAXIS_RANGE_LOWER_F,
    OSCILLOSCOPE_SET_FFTYAXIS_RANGE_UPPER,
    OSCILLOSCOPE_GET_FFTYAXIS_RANGE_UPPER,
    OSCILLOSCOPE_SET_FFTYAXIS_RANGE_UPPER_F,
    OSCILLOSCOPE_GET_FFTYAXIS_RANGE_UPPER_F,
    OSCILLOSCOPE_SET_FFTYAXIS_RANGE_REVERSED,
    OSCILLOSCOPE_GET_FFTYAXIS_RANGE_REVERSED,
    OSCILLOSCOPE_SET_FFTYAXIS_LABEL,
    OSCILLOSCOPE_GET_FFTYAXIS_LABEL,

    OSCILLOSCOPE_NEW_BAR =
    (OSCILLOSCOPE_BAR_BASE * BASE_SIZE),
    OSCILLOSCOPE_NEW_BAR_SPACER_0, // spacer
    OSCILLOSCOPE_NEW_BAR_SPACER_1, // spacer
    OSCILLOSCOPE_NEW_BAR_SPACER_2, // spacer
    OSCILLOSCOPE_REMOVE_BAR_DATA,
    OSCILLOSCOPE_REMOVE_BAR_DATA_SPACER_0, // spacer
    OSCILLOSCOPE_REMOVE_BAR_DATA_SPACER_1, // spacer
    OSCILLOSCOPE_REMOVE_BAR_DATA_SPACER_2, // spacer
    OSCILLOSCOPE_ADD_BAR_DATA_0,
    OSCILLOSCOPE_ADD_BAR_DATA_0_A,
    OSCILLOSCOPE_ADD_BAR_DATA_0_F,
    OSCILLOSCOPE_ADD_BAR_DATA_0_F_A,
    OSCILLOSCOPE_ADD_BAR_DATA_1,
    OSCILLOSCOPE_ADD_BAR_DATA_1_A,
    OSCILLOSCOPE_ADD_BAR_DATA_1_F,
    OSCILLOSCOPE_ADD_BAR_DATA_1_F_A,
    OSCILLOSCOPE_ADD_BAR_DATA_SPACER_00, // spacer
    OSCILLOSCOPE_ADD_BAR_DATA_SPACER_01, // spacer
    OSCILLOSCOPE_ADD_BAR_DATA_SPACER_02, // spacer
    OSCILLOSCOPE_ADD_BAR_DATA_SPACER_03, // spacer
    OSCILLOSCOPE_ADD_BAR_DATA_SPACER_04, // spacer
    OSCILLOSCOPE_ADD_BAR_DATA_SPACER_05, // spacer
    OSCILLOSCOPE_ADD_BAR_DATA_SPACER_06, // spacer
    OSCILLOSCOPE_ADD_BAR_DATA_SPACER_07, // spacer
    OSCILLOSCOPE_ADD_BAR_DATA_SPACER_08, // spacer
    OSCILLOSCOPE_ADD_BAR_DATA_SPACER_09, // spacer
    OSCILLOSCOPE_ADD_BAR_DATA_SPACER_10, // spacer
    OSCILLOSCOPE_ADD_BAR_DATA_SPACER_11, // spacer
    OSCILLOSCOPE_ADD_BAR_DATA_SPACER_12, // spacer
    OSCILLOSCOPE_ADD_BAR_DATA_SPACER_13, // spacer
    OSCILLOSCOPE_ADD_BAR_DATA_SPACER_14, // spacer
    OSCILLOSCOPE_ADD_BAR_DATA_SPACER_15, // spacer
    OSCILLOSCOPE_ADD_BAR_DATA_SPACER_16, // spacer
    OSCILLOSCOPE_ADD_BAR_DATA_SPACER_17, // spacer
    OSCILLOSCOPE_ADD_BAR_DATA_SPACER_18, // spacer
    OSCILLOSCOPE_ADD_BAR_DATA_SPACER_19, // spacer
    OSCILLOSCOPE_ADD_BAR_DATA_SPACER_20, // spacer
    OSCILLOSCOPE_ADD_BAR_DATA_SPACER_21, // spacer
    OSCILLOSCOPE_ADD_BAR_DATA_SPACER_22, // spacer
    OSCILLOSCOPE_ADD_BAR_DATA_SPACER_23, // spacer
    OSCILLOSCOPE_REMOVE_BAR_DATA_BEFORE,
    OSCILLOSCOPE_REMOVE_BAR_DATA_BEFORE_F,
    OSCILLOSCOPE_REMOVE_BAR_DATA_AFTER,
    OSCILLOSCOPE_REMOVE_BAR_DATA_AFTER_F,
    OSCILLOSCOPE_REMOVE_BAR_DATA_BETWEEN,
    OSCILLOSCOPE_REMOVE_BAR_DATA_BETWEEN_A,
    OSCILLOSCOPE_REMOVE_BAR_DATA_BETWEEN_F,
    OSCILLOSCOPE_REMOVE_BAR_DATA_BETWEEN_F_A,
    OSCILLOSCOPE_REMOVE_BAR_DATUM,
    OSCILLOSCOPE_REMOVE_BAR_DATUM_A,
    OSCILLOSCOPE_REMOVE_BAR_DATUM_F,
    OSCILLOSCOPE_REMOVE_BAR_DATUM_F_A,
    OSCILLOSCOPE_REMOVE_BAR_DATUM_SPACER_0, // spacer
    OSCILLOSCOPE_REMOVE_BAR_DATUM_SPACER_1, // spacer
    OSCILLOSCOPE_REMOVE_BAR_DATUM_SPACER_2, // spacer
    OSCILLOSCOPE_REMOVE_BAR_DATUM_SPACER_3, // spacer
    OSCILLOSCOPE_SET_BAR_NAME,
    OSCILLOSCOPE_GET_BAR_NAME,
    OSCILLOSCOPE_SET_BAR_COORDINATE_SYSTEM,
    OSCILLOSCOPE_GET_BAR_COORDINATE_SYSTEM,
    OSCILLOSCOPE_SET_BAR_ANGLE_UNITS,
    OSCILLOSCOPE_GET_BAR_ANGLE_UNITS,
    OSCILLOSCOPE_SET_BAR_LINE_COLOR,
    OSCILLOSCOPE_GET_BAR_LINE_COLOR,
    OSCILLOSCOPE_SET_BAR_LINE_STYLE,
    OSCILLOSCOPE_GET_BAR_LINE_STYLE,
    OSCILLOSCOPE_SET_BAR_FILL_COLOR,
    OSCILLOSCOPE_GET_BAR_FILL_COLOR,
    OSCILLOSCOPE_SET_BAR_FILL_STYLE,
    OSCILLOSCOPE_GET_BAR_FILL_STYLE,
    OSCILLOSCOPE_SET_BAR_DELTA_MODE,
    OSCILLOSCOPE_GET_BAR_DELTA_MODE,
    OSCILLOSCOPE_SET_BAR_SIZE,
    OSCILLOSCOPE_GET_BAR_SIZE,
    OSCILLOSCOPE_SET_BAR_SAMPLE_RATE,
    OSCILLOSCOPE_GET_BAR_SAMPLE_RATE,
    OSCILLOSCOPE_SET_BAR_SAMPLE_RATE_F,
    OSCILLOSCOPE_GET_BAR_SAMPLE_RATE_F,
    OSCILLOSCOPE_SET_BAR_SCALER,
    OSCILLOSCOPE_GET_BAR_SCALER,
    OSCILLOSCOPE_SET_BAR_SCALER_F,
    OSCILLOSCOPE_GET_BAR_SCALER_F,
    OSCILLOSCOPE_SET_BAR_WIDTH,
    OSCILLOSCOPE_GET_BAR_WIDTH,
    OSCILLOSCOPE_SET_BAR_WIDTH_F,
    OSCILLOSCOPE_GET_BAR_WIDTH_F,
    OSCILLOSCOPE_SET_BAR_SCATTER_STYLE,
    OSCILLOSCOPE_GET_BAR_SCATTER_STYLE,
    OSCILLOSCOPE_SET_BAR_BELOW,
    OSCILLOSCOPE_GET_BAR_BELOW,
    OSCILLOSCOPE_SET_BAR_ABOVE,
    OSCILLOSCOPE_GET_BAR_ABOVE,

    OSCILLOSCOPE_NEW_CURVE =
    (OSCILLOSCOPE_CURVE_BASE * BASE_SIZE),
    OSCILLOSCOPE_NEW_CURVE_SPACER_0, // spacer
    OSCILLOSCOPE_NEW_CURVE_SPACER_1, // spacer
    OSCILLOSCOPE_NEW_CURVE_SPACER_2, // spacer
    OSCILLOSCOPE_REMOVE_CURVE_DATA,
    OSCILLOSCOPE_REMOVE_CURVE_DATA_SPACER_0, // spacer
    OSCILLOSCOPE_REMOVE_CURVE_DATA_SPACER_1, // spacer
    OSCILLOSCOPE_REMOVE_CURVE_DATA_SAPCER_2, // spacer
    OSCILLOSCOPE_ADD_CURVE_DATA_0,
    OSCILLOSCOPE_ADD_CURVE_DATA_0_A,
    OSCILLOSCOPE_ADD_CURVE_DATA_0_F,
    OSCILLOSCOPE_ADD_CURVE_DATA_0_F_A,
    OSCILLOSCOPE_ADD_CURVE_DATA_1,
    OSCILLOSCOPE_ADD_CURVE_DATA_1_A,
    OSCILLOSCOPE_ADD_CURVE_DATA_1_F,
    OSCILLOSCOPE_ADD_CURVE_DATA_1_F_A,
    OSCILLOSCOPE_ADD_CURVE_DATA_SPACER_00, // spacer
    OSCILLOSCOPE_ADD_CURVE_DATA_SPACER_01, // spacer
    OSCILLOSCOPE_ADD_CURVE_DATA_SPACER_02, // spacer
    OSCILLOSCOPE_ADD_CURVE_DATA_SPACER_03, // spacer
    OSCILLOSCOPE_ADD_CURVE_DATA_SPACER_04, // spacer
    OSCILLOSCOPE_ADD_CURVE_DATA_SPACER_05, // spacer
    OSCILLOSCOPE_ADD_CURVE_DATA_SPACER_06, // spacer
    OSCILLOSCOPE_ADD_CURVE_DATA_SPACER_07, // spacer
    OSCILLOSCOPE_ADD_CURVE_DATA_SPACER_08, // spacer
    OSCILLOSCOPE_ADD_CURVE_DATA_SPACER_09, // spacer
    OSCILLOSCOPE_ADD_CURVE_DATA_SPACER_10, // spacer
    OSCILLOSCOPE_ADD_CURVE_DATA_SPACER_11, // spacer
    OSCILLOSCOPE_ADD_CURVE_DATA_SPACER_12, // spacer
    OSCILLOSCOPE_ADD_CURVE_DATA_SPACER_13, // spacer
    OSCILLOSCOPE_ADD_CURVE_DATA_SPACER_14, // spacer
    OSCILLOSCOPE_ADD_CURVE_DATA_SPACER_15, // spacer
    OSCILLOSCOPE_ADD_CURVE_DATA_SPACER_16, // spacer
    OSCILLOSCOPE_ADD_CURVE_DATA_SPACER_17, // spacer
    OSCILLOSCOPE_ADD_CURVE_DATA_SPACER_18, // spacer
    OSCILLOSCOPE_ADD_CURVE_DATA_SPACER_19, // spacer
    OSCILLOSCOPE_ADD_CURVE_DATA_SPACER_20, // spacer
    OSCILLOSCOPE_ADD_CURVE_DATA_SPACER_21, // spacer
    OSCILLOSCOPE_ADD_CURVE_DATA_SPACER_22, // spacer
    OSCILLOSCOPE_ADD_CURVE_DATA_SPACER_23, // spacer
    OSCILLOSCOPE_REMOVE_CURVE_DATA_BEFORE,
    OSCILLOSCOPE_REMOVE_CURVE_DATA_BEFORE_F,
    OSCILLOSCOPE_REMOVE_CURVE_DATA_AFTER,
    OSCILLOSCOPE_REMOVE_CURVE_DATA_AFTER_F,
    OSCILLOSCOPE_REMOVE_CURVE_DATA_BETWEEN,
    OSCILLOSCOPE_REMOVE_CURVE_DATA_BETWEEN_A,
    OSCILLOSCOPE_REMOVE_CURVE_DATA_BETWEEN_F,
    OSCILLOSCOPE_REMOVE_CURVE_DATA_BETWEEN_F_A,
    OSCILLOSCOPE_REMOVE_CURVE_DATUM,
    OSCILLOSCOPE_REMOVE_CURVE_DATUM_A,
    OSCILLOSCOPE_REMOVE_CURVE_DATUM_F,
    OSCILLOSCOPE_REMOVE_CURVE_DATUM_F_A,
    OSCILLOSCOPE_REMOVE_CURVE_DATUM_SPACER_0, // spacer
    OSCILLOSCOPE_REMOVE_CURVE_DATUM_SPACER_1, // spacer
    OSCILLOSCOPE_REMOVE_CURVE_DATUM_SPACER_2, // spacer
    OSCILLOSCOPE_REMOVE_CURVE_DATUM_SPACER_3, // spacer
    OSCILLOSCOPE_SET_CURVE_NAME,
    OSCILLOSCOPE_GET_CURVE_NAME,
    OSCILLOSCOPE_SET_CURVE_COORDINATE_SYSTEM,
    OSCILLOSCOPE_GET_CURVE_COORDINATE_SYSTEM,
    OSCILLOSCOPE_SET_CURVE_ANGLE_UNITS,
    OSCILLOSCOPE_GET_CURVE_ANGLE_UNITS,
    OSCILLOSCOPE_SET_CURVE_LINE_COLOR,
    OSCILLOSCOPE_GET_CURVE_LINE_COLOR,
    OSCILLOSCOPE_SET_CURVE_LINE_STYLE,
    OSCILLOSCOPE_GET_CURVE_LINE_STYLE,
    OSCILLOSCOPE_SET_CURVE_FILL_COLOR,
    OSCILLOSCOPE_GET_CURVE_FILL_COLOR,
    OSCILLOSCOPE_SET_CURVE_FILL_STYLE,
    OSCILLOSCOPE_GET_CURVE_FILL_STYLE,
    OSCILLOSCOPE_SET_CURVE_DELTA_MODE,
    OSCILLOSCOPE_GET_CURVE_DELTA_MODE,
    OSCILLOSCOPE_SET_CURVE_SIZE,
    OSCILLOSCOPE_GET_CURVE_SIZE,
    OSCILLOSCOPE_SET_CURVE_SAMPLE_RATE,
    OSCILLOSCOPE_GET_CURVE_SAMPLE_RATE,
    OSCILLOSCOPE_SET_CURVE_SAMPLE_RATE_F,
    OSCILLOSCOPE_GET_CURVE_SAMPLE_RATE_F,
    OSCILLOSCOPE_SET_CURVE_SCALER,
    OSCILLOSCOPE_GET_CURVE_SCALER,
    OSCILLOSCOPE_SET_CURVE_SCALER_F,
    OSCILLOSCOPE_GET_CURVE_SCALER_F,
    OSCILLOSCOPE_SET_CURVE_FFT,
    OSCILLOSCOPE_GET_CURVE_FFT,
    OSCILLOSCOPE_SET_CURVE_FFT_WINDOW,
    OSCILLOSCOPE_GET_CURVE_FFT_WINDOW,
    OSCILLOSCOPE_SET_CURVE_SCATTER_STYLE,
    OSCILLOSCOPE_GET_CURVE_SCATTER_STYLE,
    OSCILLOSCOPE_SET_CURVE_STYLE,
    OSCILLOSCOPE_GET_CURVE_STYLE,
    OSCILLOSCOPE_SET_CURVE_CHANNEL_FILL_CURVE,
    OSCILLOSCOPE_GET_CURVE_CHANNEL_FILL_CURVE,

    OSCILLOSCOPE_NEW_GRAPH =
    (OSCILLOSCOPE_GRAPH_BASE * BASE_SIZE),
    OSCILLOSCOPE_NEW_GRAPH_SPACER_0, // spacer
    OSCILLOSCOPE_NEW_GRAPH_SPACER_1, // spacer
    OSCILLOSCOPE_NEW_GRAPH_SPACER_2, // spacer
    OSCILLOSCOPE_REMOVE_GRAPH_DATA,
    OSCILLOSCOPE_REMOVE_GRAPH_DATA_SPACER_0, // spacer
    OSCILLOSCOPE_REMOVE_GRAPH_DATA_SPACER_1, // spacer
    OSCILLOSCOPE_REMOVE_GRAPH_DATA_SPACER_2, // spacer
    OSCILLOSCOPE_ADD_GRAPH_DATA_0,
    OSCILLOSCOPE_ADD_GRAPH_DATA_0_A,
    OSCILLOSCOPE_ADD_GRAPH_DATA_0_F,
    OSCILLOSCOPE_ADD_GRAPH_DATA_0_F_A,
    OSCILLOSCOPE_ADD_GRAPH_DATA_1,
    OSCILLOSCOPE_ADD_GRAPH_DATA_1_A,
    OSCILLOSCOPE_ADD_GRAPH_DATA_1_F,
    OSCILLOSCOPE_ADD_GRAPH_DATA_1_F_A,
    OSCILLOSCOPE_ADD_GRAPH_DATA_WITH_ERRORS_0,
    OSCILLOSCOPE_ADD_GRAPH_DATA_WITH_ERRORS_0_A,
    OSCILLOSCOPE_ADD_GRAPH_DATA_WITH_ERRORS_0_F,
    OSCILLOSCOPE_ADD_GRAPH_DATA_WITH_ERRORS_0_F_A,
    OSCILLOSCOPE_ADD_GRAPH_DATA_WITH_ERRORS_1,
    OSCILLOSCOPE_ADD_GRAPH_DATA_WITH_ERRORS_1_A,
    OSCILLOSCOPE_ADD_GRAPH_DATA_WITH_ERRORS_1_F,
    OSCILLOSCOPE_ADD_GRAPH_DATA_WITH_ERRORS_1_F_A,
    OSCILLOSCOPE_ADD_GRAPH_DATA_WITH_ERRORS_2,
    OSCILLOSCOPE_ADD_GRAPH_DATA_WITH_ERRORS_2_A,
    OSCILLOSCOPE_ADD_GRAPH_DATA_WITH_ERRORS_2_F,
    OSCILLOSCOPE_ADD_GRAPH_DATA_WITH_ERRORS_2_F_A,
    OSCILLOSCOPE_ADD_GRAPH_DATA_WITH_ERRORS_3,
    OSCILLOSCOPE_ADD_GRAPH_DATA_WITH_ERRORS_3_A,
    OSCILLOSCOPE_ADD_GRAPH_DATA_WITH_ERRORS_3_F,
    OSCILLOSCOPE_ADD_GRAPH_DATA_WITH_ERRORS_3_F_A,
    OSCILLOSCOPE_ADD_GRAPH_DATA_SPACER_0, // spacer
    OSCILLOSCOPE_ADD_GRAPH_DATA_SPACER_1, // spacer
    OSCILLOSCOPE_ADD_GRAPH_DATA_SPACER_2, // spacer
    OSCILLOSCOPE_ADD_GRAPH_DATA_SPACER_3, // spacer
    OSCILLOSCOPE_ADD_GRAPH_DATA_SPACER_4, // spacer
    OSCILLOSCOPE_ADD_GRAPH_DATA_SPACER_5, // spacer
    OSCILLOSCOPE_ADD_GRAPH_DATA_SPACER_6, // spacer
    OSCILLOSCOPE_ADD_GRAPH_DATA_SPACER_7, // spacer
    OSCILLOSCOPE_REMOVE_GRAPH_DATA_BEFORE,
    OSCILLOSCOPE_REMOVE_GRAPH_DATA_BEFORE_F,
    OSCILLOSCOPE_REMOVE_GRAPH_DATA_AFTER,
    OSCILLOSCOPE_REMOVE_GRAPH_DATA_AFTER_F,
    OSCILLOSCOPE_REMOVE_GRAPH_DATA_BETWEEN,
    OSCILLOSCOPE_REMOVE_GRAPH_DATA_BETWEEN_A,
    OSCILLOSCOPE_REMOVE_GRAPH_DATA_BETWEEN_F,
    OSCILLOSCOPE_REMOVE_GRAPH_DATA_BETWEEN_F_A,
    OSCILLOSCOPE_REMOVE_GRAPH_DATUM,
    OSCILLOSCOPE_REMOVE_GRAPH_DATUM_A,
    OSCILLOSCOPE_REMOVE_GRAPH_DATUM_F,
    OSCILLOSCOPE_REMOVE_GRAPH_DATUM_F_A,
    OSCILLOSCOPE_REMOVE_GRAPH_DATUM_SPACER_0, // spacer
    OSCILLOSCOPE_REMOVE_GRAPH_DATUM_SPACER_1, // spacer
    OSCILLOSCOPE_REMOVE_GRAPH_DATUM_SPACER_2, // spacer
    OSCILLOSCOPE_REMOVE_GRAPH_DATUM_SPACER_3, // spacer
    OSCILLOSCOPE_SET_GRAPH_NAME,
    OSCILLOSCOPE_GET_GRAPH_NAME,
    OSCILLOSCOPE_SET_GRAPH_COORDINATE_SYSTEM,
    OSCILLOSCOPE_GET_GRAPH_COORDINATE_SYSTEM,
    OSCILLOSCOPE_SET_GRAPH_ANGLE_UNITS,
    OSCILLOSCOPE_GET_GRAPH_ANGLE_UNITS,
    OSCILLOSCOPE_SET_GRAPH_LINE_COLOR,
    OSCILLOSCOPE_GET_GRAPH_LINE_COLOR,
    OSCILLOSCOPE_SET_GRAPH_LINE_STYLE,
    OSCILLOSCOPE_GET_GRAPH_LINE_STYLE,
    OSCILLOSCOPE_SET_GRAPH_FILL_COLOR,
    OSCILLOSCOPE_GET_GRAPH_FILL_COLOR,
    OSCILLOSCOPE_SET_GRAPH_FILL_STYLE,
    OSCILLOSCOPE_GET_GRAPH_FILL_STYLE,
    OSCILLOSCOPE_SET_GRAPH_DELTA_MODE,
    OSCILLOSCOPE_GET_GRAPH_DELTA_MODE,
    OSCILLOSCOPE_SET_GRAPH_SIZE,
    OSCILLOSCOPE_GET_GRAPH_SIZE,
    OSCILLOSCOPE_SET_GRAPH_SAMPLE_RATE,
    OSCILLOSCOPE_GET_GRAPH_SAMPLE_RATE,
    OSCILLOSCOPE_SET_GRAPH_SAMPLE_RATE_F,
    OSCILLOSCOPE_GET_GRAPH_SAMPLE_RATE_F,
    OSCILLOSCOPE_SET_GRAPH_SCALER,
    OSCILLOSCOPE_GET_GRAPH_SCALER,
    OSCILLOSCOPE_SET_GRAPH_SCALER_F,
    OSCILLOSCOPE_GET_GRAPH_SCALER_F,
    OSCILLOSCOPE_SET_GRAPH_FFT,
    OSCILLOSCOPE_GET_GRAPH_FFT,
    OSCILLOSCOPE_SET_GRAPH_FFT_WINDOW,
    OSCILLOSCOPE_GET_GRAPH_FFT_WINDOW,
    OSCILLOSCOPE_SET_GRAPH_SCATTER_STYLE,
    OSCILLOSCOPE_GET_GRAPH_SCATTER_STYLE,
    OSCILLOSCOPE_SET_GRAPH_STYLE,
    OSCILLOSCOPE_GET_GRAPH_STYLE,
    OSCILLOSCOPE_SET_GRAPH_CHANNEL_FILL_GRAPH,
    OSCILLOSCOPE_GET_GRAPH_CHANNEL_FILL_GRAPH,
    OSCILLOSCOPE_SET_GRAPH_KEY_ERRORS,
    OSCILLOSCOPE_GET_GRAPH_KEY_ERRORS,
    OSCILLOSCOPE_SET_GRAPH_VALUE_ERRORS,
    OSCILLOSCOPE_GET_GRAPH_VALUE_ERRORS,

    OSCILLOSCOPE_NEW_BOX =
    (OSCILLOSCOPE_BOX_BASE * BASE_SIZE),
    OSCILLOSCOPE_NEW_BOX_SPACER_0, // spacer
    OSCILLOSCOPE_NEW_BOX_SPACER_1, // spacer
    OSCILLOSCOPE_NEW_BOX_SPACER_2, // spacer
    OSCILLOSCOPE_REMOVE_BOX_DATA,
    OSCILLOSCOPE_REMOVE_BOX_DATA_SPACER_0, // spacer
    OSCILLOSCOPE_REMOVE_BOX_DATA_SPACER_1, // spacer
    OSCILLOSCOPE_REMOVE_BOX_DATA_SPACER_2, // spacer
    OSCILLOSCOPE_ADD_BOX_DATA_0,
    OSCILLOSCOPE_ADD_BOX_DATA_0_A,
    OSCILLOSCOPE_ADD_BOX_DATA_0_F,
    OSCILLOSCOPE_ADD_BOX_DATA_0_F_A,
    OSCILLOSCOPE_ADD_BOX_DATA_1,
    OSCILLOSCOPE_ADD_BOX_DATA_1_A,
    OSCILLOSCOPE_ADD_BOX_DATA_1_F,
    OSCILLOSCOPE_ADD_BOX_DATA_1_F_A,
    OSCILLOSCOPE_ADD_BOX_DATA_SPACER_00, // spacer
    OSCILLOSCOPE_ADD_BOX_DATA_SPACER_01, // spacer
    OSCILLOSCOPE_ADD_BOX_DATA_SPACER_02, // spacer
    OSCILLOSCOPE_ADD_BOX_DATA_SPACER_03, // spacer
    OSCILLOSCOPE_ADD_BOX_DATA_SPACER_04, // spacer
    OSCILLOSCOPE_ADD_BOX_DATA_SPACER_05, // spacer
    OSCILLOSCOPE_ADD_BOX_DATA_SPACER_06, // spacer
    OSCILLOSCOPE_ADD_BOX_DATA_SPACER_07, // spacer
    OSCILLOSCOPE_ADD_BOX_DATA_SPACER_08, // spacer
    OSCILLOSCOPE_ADD_BOX_DATA_SPACER_09, // spacer
    OSCILLOSCOPE_ADD_BOX_DATA_SPACER_10, // spacer
    OSCILLOSCOPE_ADD_BOX_DATA_SPACER_11, // spacer
    OSCILLOSCOPE_ADD_BOX_DATA_SPACER_12, // spacer
    OSCILLOSCOPE_ADD_BOX_DATA_SPACER_13, // spacer
    OSCILLOSCOPE_ADD_BOX_DATA_SPACER_14, // spacer
    OSCILLOSCOPE_ADD_BOX_DATA_SPACER_15, // spacer
    OSCILLOSCOPE_ADD_BOX_DATA_SPACER_16, // spacer
    OSCILLOSCOPE_ADD_BOX_DATA_SPACER_17, // spacer
    OSCILLOSCOPE_ADD_BOX_DATA_SPACER_18, // spacer
    OSCILLOSCOPE_ADD_BOX_DATA_SPACER_19, // spacer
    OSCILLOSCOPE_ADD_BOX_DATA_SPACER_20, // spacer
    OSCILLOSCOPE_ADD_BOX_DATA_SPACER_21, // spacer
    OSCILLOSCOPE_ADD_BOX_DATA_SPACER_22, // spacer
    OSCILLOSCOPE_ADD_BOX_DATA_SPACER_23, // spacer
    OSCILLOSCOPE_REMOVE_BOX_DATA_BEFORE,
    OSCILLOSCOPE_REMOVE_BOX_DATA_BEFORE_F,
    OSCILLOSCOPE_REMOVE_BOX_DATA_AFTER,
    OSCILLOSCOPE_REMOVE_BOX_DATA_AFTER_F,
    OSCILLOSCOPE_REMOVE_BOX_DATA_BETWEEN,
    OSCILLOSCOPE_REMOVE_BOX_DATA_BETWEEN_A,
    OSCILLOSCOPE_REMOVE_BOX_DATA_BETWEEN_F,
    OSCILLOSCOPE_REMOVE_BOX_DATA_BETWEEN_F_A,
    OSCILLOSCOPE_REMOVE_BOX_DATUM,
    OSCILLOSCOPE_REMOVE_BOX_DATUM_A,
    OSCILLOSCOPE_REMOVE_BOX_DATUM_F,
    OSCILLOSCOPE_REMOVE_BOX_DATUM_F_A,
    OSCILLOSCOPE_REMOVE_BOX_DATUM_SPACER_0, // spacer
    OSCILLOSCOPE_REMOVE_BOX_DATUM_SPACER_1, // spacer
    OSCILLOSCOPE_REMOVE_BOX_DATUM_SPACER_2, // spacer
    OSCILLOSCOPE_REMOVE_BOX_DATUM_SPACER_3, // spacer
    OSCILLOSCOPE_SET_BOX_NAME,
    OSCILLOSCOPE_GET_BOX_NAME,
    OSCILLOSCOPE_SET_BOX_COORDINATE_SYSTEM,
    OSCILLOSCOPE_GET_BOX_COORDINATE_SYSTEM,
    OSCILLOSCOPE_SET_BOX_ANGLE_UNITS,
    OSCILLOSCOPE_GET_BOX_ANGLE_UNITS,
    OSCILLOSCOPE_SET_BOX_LINE_COLOR,
    OSCILLOSCOPE_GET_BOX_LINE_COLOR,
    OSCILLOSCOPE_SET_BOX_LINE_STYLE,
    OSCILLOSCOPE_GET_BOX_LINE_STYLE,
    OSCILLOSCOPE_SET_BOX_FILL_COLOR,
    OSCILLOSCOPE_GET_BOX_FILL_COLOR,
    OSCILLOSCOPE_SET_BOX_FILL_STYLE,
    OSCILLOSCOPE_GET_BOX_FILL_STYLE,
    OSCILLOSCOPE_SET_BOX_DELTA_MODE,
    OSCILLOSCOPE_GET_BOX_DELTA_MODE,
    OSCILLOSCOPE_SET_BOX_SIZE,
    OSCILLOSCOPE_GET_BOX_SIZE,
    OSCILLOSCOPE_SET_BOX_SAMPLE_RATE,
    OSCILLOSCOPE_GET_BOX_SAMPLE_RATE,
    OSCILLOSCOPE_SET_BOX_SAMPLE_RATE_F,
    OSCILLOSCOPE_GET_BOX_SAMPLE_RATE_F,
    OSCILLOSCOPE_SET_BOX_SCALER,
    OSCILLOSCOPE_GET_BOX_SCALER,
    OSCILLOSCOPE_SET_BOX_SCALER_F,
    OSCILLOSCOPE_GET_BOX_SCALER_F,
    OSCILLOSCOPE_SET_BOX_WIDTH,
    OSCILLOSCOPE_GET_BOX_WIDTH,
    OSCILLOSCOPE_SET_BOX_WIDTH_F,
    OSCILLOSCOPE_GET_BOX_WIDTH_F,
    OSCILLOSCOPE_SET_BOX_SCATTER_STYLE,
    OSCILLOSCOPE_GET_BOX_SCATTER_STYLE,
    OSCILLOSCOPE_SET_BOX_KEY,
    OSCILLOSCOPE_GET_BOX_KEY,
    OSCILLOSCOPE_SET_BOX_KEY_F,
    OSCILLOSCOPE_GET_BOX_KEY_F,
    OSCILLOSCOPE_SET_BOX_MINIMUM,
    OSCILLOSCOPE_GET_BOX_MINIMUM,
    OSCILLOSCOPE_SET_BOX_MINIMUM_F,
    OSCILLOSCOPE_GET_BOX_MINIMUM_F,
    OSCILLOSCOPE_SET_BOX_LOWER_QUARTILE,
    OSCILLOSCOPE_GET_BOX_LOWER_QUARTILE,
    OSCILLOSCOPE_SET_BOX_LOWER_QUARTILE_F,
    OSCILLOSCOPE_GET_BOX_LOWER_QUARTILE_F,
    OSCILLOSCOPE_SET_BOX_MEDIAN,
    OSCILLOSCOPE_GET_BOX_MEDIAN,
    OSCILLOSCOPE_SET_BOX_MEDIAN_F,
    OSCILLOSCOPE_GET_BOX_MEDIAN_F,
    OSCILLOSCOPE_SET_BOX_UPPER_QUARTILE,
    OSCILLOSCOPE_GET_BOX_UPPER_QUARTILE,
    OSCILLOSCOPE_SET_BOX_UPPER_QUARTILE_F,
    OSCILLOSCOPE_GET_BOX_UPPER_QUARTILE_F,
    OSCILLOSCOPE_SET_BOX_MAXIMUM,
    OSCILLOSCOPE_GET_BOX_MAXIMUM,
    OSCILLOSCOPE_SET_BOX_MAXIMUM_F,
    OSCILLOSCOPE_GET_BOX_MAXIMUM_F,

    // Serial Table

    TABLE_NEW_UNDOCKED_WINDOW =
    (TABLE_BASE * BASE_SIZE),
    TABLE_NEW_UNDOCKED_WINDOW_SPACER_0, // spacer
    TABLE_NEW_UNDOCKED_WINDOW_SPACER_1, // spacer
    TABLE_NEW_UNDOCKED_WINDOW_SPACER_2, // spacer
    TABLE_NEW_DOCKED_WINDOW,
    TABLE_NEW_DOCKED_WINDOW_SPACER_0, // spacer
    TABLE_NEW_DOCKED_WINDOW_SPACER_1, // spacer
    TABLE_NEW_DOCKED_WINDOW_SPACER_2, // spacer
    TABLE_NEW_MAIN_DOCKED_WINDOW,
    TABLE_NEW_MAIN_DOCKED_WINDOW_SPACER_0, // spacer
    TABLE_NEW_MAIN_DOCKED_WINDOW_SPACER_1, // spacer
    TABLE_NEW_MAIN_DOCKED_WINDOW_SPACER_2, // spacer
    TABLE_CLEAR_ALL,
    TABLE_CLEAR_ALL_SPACER_0, // spacer
    TABLE_CLEAR_ALL_SPACER_1, // spacer
    TABLE_CLEAR_ALL_SPACER_2, // spacer
    TABLE_NEW_ITEM,
    TABLE_NEW_ITEM_SPACER_0, // spacer
    TABLE_NEW_ITEM_SPACER_1, // spacer
    TABLE_NEW_ITEM_SPACER_2, // spacer
    TABLE_DELETE_ITEM,
    TABLE_DELETE_ITEMS,
    TABLE_DELETE_ITEMS_IN_ROW,
    TABLE_DELETE_ITEMS_IN_COLUMN,
    TABLE_DELETE_ITEM_SPACER_0, // spacer
    TABLE_DELETE_ITEM_SPACER_1, // spacer
    TABLE_DELETE_ITEM_SPACER_2, // spacer
    TABLE_DELETE_ITEM_SPACER_3, // spacer
    TABLE_SET_ITEM_TEXT,
    TABLE_GET_ITEM_TEXT,

    TABLE_NEW_ROW =
    (TABLE_ROW_BASE * BASE_SIZE),
    TABLE_NEW_ROW_SPACER_0, // spacer
    TABLE_NEW_ROW_SPACER_1, // spacer
    TABLE_NEW_ROW_SPACER_2, // spacer
    TABLE_NEW_ROW_SPACER_3, // spacer
    TABLE_NEW_ROW_SPACER_4, // spacer
    TABLE_NEW_ROW_SPACER_5, // spacer
    TABLE_NEW_ROW_SPACER_6, // spacer
    TABLE_DELETE_ROW,
    TABLE_DELETE_ROWS,
    TABLE_DELETE_ROW_SPACER_0, // spacer
    TABLE_DELETE_ROW_SPACER_1, // spacer
    TABLE_DELETE_ROW_SPACER_2, // spacer
    TABLE_DELETE_ROW_SPACER_3, // spacer
    TABLE_DELETE_ROW_SPACER_4, // spacer
    TABLE_DELETE_ROW_SPACER_5, // spacer
    TABLE_SET_ROW_NAME,
    TABLE_GET_ROW_NAME,

    TABLE_NEW_COLUMN =
    (TABLE_COLUMN_BASE * BASE_SIZE),
    TABLE_NEW_COLUMN_SPACER_0, // spacer
    TABLE_NEW_COLUMN_SPACER_1, // spacer
    TABLE_NEW_COLUMN_SPACER_2, // spacer
    TABLE_NEW_COLUMN_SPACER_3, // spacer
    TABLE_NEW_COLUMN_SPACER_4, // spacer
    TABLE_NEW_COLUMN_SPACER_5, // spacer
    TABLE_NEW_COLUMN_SPACER_6, // spacer
    TABLE_DELETE_COLUMN,
    TABLE_DELETE_COLUMNS,
    TABLE_DELETE_COLUMN_SPACER_0, // spacer
    TABLE_DELETE_COLUMN_SPACER_1, // spacer
    TABLE_DELETE_COLUMN_SPACER_2, // spacer
    TABLE_DELETE_COLUMN_SPACER_3, // spacer
    TABLE_DELETE_COLUMN_SPACER_4, // spacer
    TABLE_DELETE_COLUMN_SPACER_5, // spacer
    TABLE_SET_COLUMN_NAME,
    TABLE_GET_COLUMN_NAME,

    // Serial Tree

    TREE_NEW_UNDOCKED_WINDOW =
    (TREE_BASE * BASE_SIZE),
    TREE_NEW_UNDOCKED_WINDOW_SPACER_0, // spacer
    TREE_NEW_UNDOCKED_WINDOW_SPACER_1, // spacer
    TREE_NEW_UNDOCKED_WINDOW_SPACER_2, // spacer
    TREE_NEW_DOCKED_WINDOW,
    TREE_NEW_DOCKED_WINDOW_SPACER_0, // spacer
    TREE_NEW_DOCKED_WINDOW_SPACER_1, // spacer
    TREE_NEW_DOCKED_WINDOW_SPACER_2, // spacer
    TREE_NEW_MAIN_DOCKED_WINDOW,
    TREE_NEW_MAIN_DOCKED_WINDOW_SPACER_0, // spacer
    TREE_NEW_MAIN_DOCKED_WINDOW_SPACER_1, // spacer
    TREE_NEW_MAIN_DOCKED_WINDOW_SPACER_2, // spacer
    TREE_CLEAR_ALL,
    TREE_CLEAR_ALL_SPACER_0, // spacer
    TREE_CLEAR_ALL_SPACER_1, // spacer
    TREE_CLEAR_ALL_SPACER_2, // spacer
    TREE_NEW_ITEM,
    TREE_NEW_ITEM_SPACER_0, // spacer
    TREE_NEW_ITEM_SPACER_1, // spacer
    TREE_NEW_ITEM_SPACER_2, // spacer
    TREE_DELETE_ITEM,
    TREE_DELETE_ITEMS,
    TREE_DELETE_ITEM_SPACER_0, // spacer
    TREE_DELETE_ITEM_SPACER_1, // spacer
    TREE_DELETE_ITEM_SPACER_2, // spacer
    TREE_DELETE_ITEM_SPACER_3, // spacer
    TREE_DELETE_ITEM_SPACER_4, // spacer
    TREE_DELETE_ITEM_SPACER_5, // spacer
    TREE_SET_ITEM_VALUE,
    TREE_GET_ITEM_VALUE,

    // Serial Graphics

    GRAPHICS_NEW_UNDOCKED_WINDOW =
    (GRAPHICS_BASE * BASE_SIZE),
    GRAPHICS_NEW_UNDOCKED_WINDOW_SPACER_0, // spacer
    GRAPHICS_NEW_UNDOCKED_WINDOW_SPACER_1, // spacer
    GRAPHICS_NEW_UNDOCKED_WINDOW_SPACER_2, // spacer
    GRAPHICS_NEW_DOCKED_WINDOW,
    GRAPHICS_NEW_DOCKED_WINDOW_SPACER_0, // spacer
    GRAPHICS_NEW_DOCKED_WINDOW_SPACER_1, // spacer
    GRAPHICS_NEW_DOCKED_WINDOW_SPACER_2, // spacer
    GRAPHICS_NEW_MAIN_DOCKED_WINDOW,
    GRAPHICS_NEW_MAIN_DOCKED_WINDOW_SPACER_0, // spacer
    GRAPHICS_NEW_MAIN_DOCKED_WINDOW_SPACER_1, // spacer
    GRAPHICS_NEW_MAIN_DOCKED_WINDOW_SPACER_2, // spacer
    GRAPHICS_CLEAR_ALL_0,
    GRAPHICS_CLEAR_ALL_0_A,
    GRAPHICS_CLEAR_ALL_0_F,
    GRAPHICS_CLEAR_ALL_0_F_A,
    GRAPHICS_CLEAR_ALL_1,
    GRAPHICS_CLEAR_ALL_SPACER_0, // spacer
    GRAPHICS_CLEAR_ALL_SPACER_1, // spacer
    GRAPHICS_CLEAR_ALL_SPACER_2, // spacer
    GRAPHICS_CLEAR_ALL_SPACER_3, // spacer
    GRAPHICS_CLEAR_ALL_SPACER_4, // spacer
    GRAPHICS_DRAW_TEXT,
    GRAPHICS_DRAW_TEXT_A,
    GRAPHICS_DRAW_TEXT_F,
    GRAPHICS_DRAW_TEXT_F_A,
    GRAPHICS_DRAW_LINE,
    GRAPHICS_DRAW_LINE_A,
    GRAPHICS_DRAW_LINE_F,
    GRAPHICS_DRAW_LINE_F_A,
    GRAPHICS_DRAW_QUADRATIC_LINE,
    GRAPHICS_DRAW_QUADRATIC_LINE_A,
    GRAPHICS_DRAW_QUADRATIC_LINE_F,
    GRAPHICS_DRAW_QUADRATIC_LINE_F_A,
    GRAPHICS_DRAW_CUBIC_LINE,
    GRAPHICS_DRAW_CUBIC_LINE_A,
    GRAPHICS_DRAW_CUBIC_LINE_F,
    GRAPHICS_DRAW_CUBIC_LINE_F_A,
    GRAPHICS_DRAW_ARC,
    GRAPHICS_DRAW_ARC_A,
    GRAPHICS_DRAW_ARC_F,
    GRAPHICS_DRAW_ARC_F_A,
    GRAPHICS_DRAW_CHORD,
    GRAPHICS_DRAW_CHORD_A,
    GRAPHICS_DRAW_CHORD_F,
    GRAPHICS_DRAW_CHORD_F_A,
    GRAPHICS_DRAW_TRIANGLE,
    GRAPHICS_DRAW_TRIANGLE_A,
    GRAPHICS_DRAW_TRIANGLE_F,
    GRAPHICS_DRAW_TRIANGLE_F_A,
    GRAPHICS_DRAW_QUADRILATERAL,
    GRAPHICS_DRAW_QUADRILATERAL_A,
    GRAPHICS_DRAW_QUADRILATERAL_F,
    GRAPHICS_DRAW_QUADRILATERAL_F_A,
    GRAPHICS_DRAW_RECTANGLE,
    GRAPHICS_DRAW_RECTANGLE_A,
    GRAPHICS_DRAW_RECTANGLE_F,
    GRAPHICS_DRAW_RECTANGLE_F_A,
    GRAPHICS_DRAW_ELLIPSE,
    GRAPHICS_DRAW_ELLIPSE_A,
    GRAPHICS_DRAW_ELLIPSE_F,
    GRAPHICS_DRAW_ELLIPSE_F_A,
    GRAPHICS_DRAW_SPACER_00, // spacer
    GRAPHICS_DRAW_SPACER_01, // spacer
    GRAPHICS_DRAW_SPACER_02, // spacer
    GRAPHICS_DRAW_SPACER_03, // spacer
    GRAPHICS_DRAW_SPACER_04, // spacer
    GRAPHICS_DRAW_SPACER_05, // spacer
    GRAPHICS_DRAW_SPACER_06, // spacer
    GRAPHICS_DRAW_SPACER_07, // spacer
    GRAPHICS_DRAW_SPACER_08, // spacer
    GRAPHICS_DRAW_SPACER_09, // spacer
    GRAPHICS_DRAW_SPACER_10, // spacer
    GRAPHICS_DRAW_SPACER_11, // spacer
    GRAPHICS_DRAW_SPACER_12, // spacer
    GRAPHICS_DRAW_SPACER_13, // spacer
    GRAPHICS_DRAW_SPACER_14, // spacer
    GRAPHICS_DRAW_SPACER_15, // spacer
    GRAPHICS_DRAW_SPACER_16, // spacer
    GRAPHICS_DRAW_SPACER_17, // spacer
    GRAPHICS_DRAW_SPACER_18, // spacer
    GRAPHICS_DRAW_SPACER_19, // spacer
    GRAPHICS_DRAW_SPACER_20, // spacer
    GRAPHICS_DRAW_SPACER_21, // spacer
    GRAPHICS_DRAW_SPACER_22, // spacer
    GRAPHICS_DRAW_SPACER_23, // spacer
    GRAPHICS_DRAW_SPACER_24, // spacer
    GRAPHICS_DRAW_SPACER_25, // spacer
    GRAPHICS_DRAW_SPACER_26, // spacer
    GRAPHICS_DRAW_SPACER_27, // spacer
    GRAPHICS_DRAW_SPACER_28, // spacer
    GRAPHICS_DRAW_SPACER_29, // spacer
    GRAPHICS_DRAW_SPACER_30, // spacer
    GRAPHICS_DRAW_SPACER_31, // spacer
    GRAPHICS_DRAW_SPACER_32, // spacer
    GRAPHICS_DRAW_SPACER_33, // spacer
    GRAPHICS_DRAW_SPACER_34, // spacer
    GRAPHICS_DRAW_SPACER_35, // spacer
    GRAPHICS_DRAW_SPACER_36, // spacer
    GRAPHICS_DRAW_SPACER_37, // spacer
    GRAPHICS_DRAW_SPACER_38, // spacer
    GRAPHICS_DRAW_SPACER_39, // spacer
    GRAPHICS_SET_BACKGROUND_COLOR,
    GRAPHICS_GET_BACKGROUND_COLOR,
    GRAPHICS_SET_COORDINATE_SYSTEM,
    GRAPHICS_GET_COORDINATE_SYSTEM,
    GRAPHICS_SET_ANGLE_UNITS,
    GRAPHICS_GET_ANGLE_UNITS,
    GRAPHICS_SET_LINE_COLOR,
    GRAPHICS_GET_LINE_COLOR,
    GRAPHICS_SET_LINE_STYLE,
    GRAPHICS_GET_LINE_STYLE,
    GRAPHICS_SET_FILL_COLOR,
    GRAPHICS_GET_FILL_COLOR,
    GRAPHICS_SET_FILL_STYLE,
    GRAPHICS_GET_FILL_STYLE,
    GRAPHICS_SET_ROTATION,
    GRAPHICS_GET_ROTATION,
    GRAPHICS_SET_ROTATION_F,
    GRAPHICS_GET_ROTATION_F,
    GRAPHICS_SET_SCALE,
    GRAPHICS_GET_SCALE,
    GRAPHICS_SET_SCALE_F,
    GRAPHICS_GET_SCALE_F,

    // Serial Interface

    INTERFACE_NEW_UNDOCKED_WINDOW =
    (INTERFACE_BASE * BASE_SIZE),
    INTERFACE_NEW_UNDOCKED_WINDOW_SPACER_0, // spacer
    INTERFACE_NEW_UNDOCKED_WINDOW_SPACER_1, // spacer
    INTERFACE_NEW_UNDOCKED_WINDOW_SPACER_2, // spacer
    INTERFACE_NEW_DOCKED_WINDOW,
    INTERFACE_NEW_DOCKED_WINDOW_SPACER_0, // spacer
    INTERFACE_NEW_DOCKED_WINDOW_SPACER_1, // spacer
    INTERFACE_NEW_DOCKED_WINDOW_SPACER_2, // spacer
    INTERFACE_NEW_MAIN_DOCKED_WINDOW,
    INTERFACE_NEW_MAIN_DOCKED_WINDOW_SPACER_0, // spacer
    INTERFACE_NEW_MAIN_DOCKED_WINDOW_SPACER_1, // spacer
    INTERFACE_NEW_MAIN_DOCKED_WINDOW_SPACER_2, // spacer
    INTERFACE_DELETE_INTERFACE_BOX,
    INTERFACE_DELETE_ALL_INTERFACE_BOXES_0,
    INTERFACE_DELETE_ALL_INTERFACE_BOXES_1,
    INTERFACE_DELETE_GROUP_BOX,
    INTERFACE_DELETE_ALL_GROUP_BOXES,
    INTERFACE_DELETE_ALL_GROUP_BOXES_SPACER, // spacer

    INTERFACE_NEW_GROUP_BOX =
    (INTERFACE_GROUP_BOX_BASE * BASE_SIZE),
    INTERFACE_NEW_GROUP_BOX_SPACER_0, // spacer
    INTERFACE_NEW_GROUP_BOX_SPACER_1, // spacer
    INTERFACE_NEW_GROUP_BOX_SPACER_2, // spacer
    INTERFACE_RESET_GROUP_BOX_SPACER_0, // spacer
    INTERFACE_RESET_GROUP_BOX_SPACER_1, // spacer
    INTERFACE_RESET_GROUP_BOX_SPACER_2, // spacer
    INTERFACE_RESET_GROUP_BOX_SPACER_3, // spacer
    INTERFACE_GROUP_BOX_SIGNAL_SPACER_0, // spacer
    INTERFACE_GROUP_BOX_SIGNAL_SPACER_1, // spacer
    INTERFACE_GROUP_BOX_SIGNAL_SPACER_2, // spacer
    INTERFACE_GROUP_BOX_SIGNAL_SPACER_3, // spacer
    INTERFACE_SET_GROUP_BOX_NAME,
    INTERFACE_GET_GROUP_BOX_NAME,

    INTERFACE_NEW_PUSH_BUTTON =
    (INTERFACE_PUSH_BUTTON_BASE * BASE_SIZE),
    INTERFACE_NEW_PUSH_BUTTON_SPACER_0, // spacer
    INTERFACE_NEW_PUSH_BUTTON_SPACER_1, // spacer
    INTERFACE_NEW_PUSH_BUTTON_SPACER_2, // spacer
    INTERFACE_RESET_PUSH_BUTTON_SPACER_0, // spacer
    INTERFACE_RESET_PUSH_BUTTON_SPACER_1, // spacer
    INTERFACE_RESET_PUSH_BUTTON_SPACER_2, // spacer
    INTERFACE_RESET_PUSH_BUTTON_SPACER_3, // spacer
    INTERFACE_PUSH_BUTTON_SIGNAL,
    INTERFACE_PUSH_BUTTON_SIGNAL_SPACER_0, // spacer
    INTERFACE_PUSH_BUTTON_SIGNAL_SPACER_1, // spacer
    INTERFACE_PUSH_BUTTON_SIGNAL_SPACER_2, // spacer
    INTERFACE_SET_PUSH_BUTTON_NAME,
    INTERFACE_GET_PUSH_BUTTON_NAME,

    INTERFACE_NEW_RADIO_BUTTON =
    (INTERFACE_RADIO_BUTTON_BASE * BASE_SIZE),
    INTERFACE_NEW_RADIO_BUTTON_SPACER_0, // spacer
    INTERFACE_NEW_RADIO_BUTTON_SPACER_1, // spacer
    INTERFACE_NEW_RADIO_BUTTON_SPACER_2, // spacer
    INTERFACE_RESET_RADIO_BUTTON_SPACER_0, // spacer
    INTERFACE_RESET_RADIO_BUTTON_SPACER_1, // spacer
    INTERFACE_RESET_RADIO_BUTTON_SPACER_2, // spacer
    INTERFACE_RESET_RADIO_BUTTON_SPACER_3, // spacer
    INTERFACE_RADIO_BUTTON_SIGNAL,
    INTERFACE_RADIO_BUTTON_SIGNAL_SPACER_0, // spacer
    INTERFACE_RADIO_BUTTON_SIGNAL_SPACER_1, // spacer
    INTERFACE_RADIO_BUTTON_SIGNAL_SPACER_2, // spacer
    INTERFACE_SET_RADIO_BUTTON_NAME,
    INTERFACE_GET_RADIO_BUTTON_NAME,
    INTERFACE_SET_RADIO_BUTTON_CHECKED,
    INTERFACE_GET_RADIO_BUTTON_CHECKED,

    INTERFACE_NEW_CHECK_BOX =
    (INTERFACE_CHECK_BOX_BASE * BASE_SIZE),
    INTERFACE_NEW_CHECK_BOX_SPACER_0, // spacer
    INTERFACE_NEW_CHECK_BOX_SPACER_1, // spacer
    INTERFACE_NEW_CHECK_BOX_SPACER_2, // spacer
    INTERFACE_RESET_CHECK_BOX_SPACER_0, // spacer
    INTERFACE_RESET_CHECK_BOX_SPACER_1, // spacer
    INTERFACE_RESET_CHECK_BOX_SPACER_2, // spacer
    INTERFACE_RESET_CHECK_BOX_SPACER_3, // spacer
    INTERFACE_CHECK_BOX_SIGNAL,
    INTERFACE_CHECK_BOX_SIGNAL_SPACER_0, // spacer
    INTERFACE_CHECK_BOX_SIGNAL_SPACER_1, // spacer
    INTERFACE_CHECK_BOX_SIGNAL_SPACER_2, // spacer
    INTERFACE_SET_CHECK_BOX_NAME,
    INTERFACE_GET_CHECK_BOX_NAME,
    INTERFACE_SET_CHECK_BOX_CHECKED,
    INTERFACE_GET_CHECK_BOX_CHECKED,

    INTERFACE_NEW_LINE_EDIT =
    (INTERFACE_LINE_EDIT_BASE * BASE_SIZE),
    INTERFACE_NEW_LINE_EDIT_SPACER_0, // spacer
    INTERFACE_NEW_LINE_EDIT_SPACER_1, // spacer
    INTERFACE_NEW_LINE_EDIT_SPACER_2, // spacer
    INTERFACE_RESET_LINE_EDIT,
    INTERFACE_RESET_LINE_EDIT_SPACER_1, // spacer
    INTERFACE_RESET_LINE_EDIT_SPACER_2, // spacer
    INTERFACE_RESET_LINE_EDIT_SPACER_3, // spacer
    INTERFACE_LINE_EDIT_SIGNAL,
    INTERFACE_LINE_EDIT_SIGNAL_SPACER_0, // spacer
    INTERFACE_LINE_EDIT_SIGNAL_SPACER_1, // spacer
    INTERFACE_LINE_EDIT_SIGNAL_SPACER_2, // spacer
    INTERFACE_SET_LINE_EDIT_NAME,
    INTERFACE_GET_LINE_EDIT_NAME,
    INTERFACE_SET_LINE_EDIT_ECHO_MODE,
    INTERFACE_GET_LINE_EDIT_ECHO_MODE,
    INTERFACE_SET_LINE_EDIT_INPUT_MASK,
    INTERFACE_GET_LINE_EDIT_INPUT_MASK,
    INTERFACE_SET_LINE_EDIT_PLACEHOLDER_TEXT,
    INTERFACE_GET_LINE_EDIT_PLACEHOLDER_TEXT,
    INTERFACE_SET_LINE_EDIT_TEXT,
    INTERFACE_GET_LINE_EDIT_TEXT,

    INTERFACE_NEW_INT_SPIN_BOX =
    (INTERFACE_INT_SPIN_BOX_BASE * BASE_SIZE),
    INTERFACE_NEW_INT_SPIN_BOX_SPACER_0, // spacer
    INTERFACE_NEW_INT_SPIN_BOX_SPACER_1, // spacer
    INTERFACE_NEW_INT_SPIN_BOX_SPACER_2, // spacer
    INTERFACE_RESET_INT_SPIN_BOX,
    INTERFACE_RESET_INT_SPIN_BOX_SPACER_0, // spacer
    INTERFACE_RESET_INT_SPIN_BOX_SPACER_1, // spacer
    INTERFACE_RESET_INT_SPIN_BOX_SPACER_2, // spacer
    INTERFACE_INT_SPIN_BOX_SIGNAL,
    INTERFACE_INT_SPIN_BOX_SIGNAL_SPACER_0, // spacer
    INTERFACE_INT_SPIN_BOX_SIGNAL_SPACER_1, // spacer
    INTERFACE_INT_SPIN_BOX_SIGNAL_SPACER_2, // spacer
    INTERFACE_SET_INT_SPIN_BOX_NAME,
    INTERFACE_GET_INT_SPIN_BOX_NAME,
    INTERFACE_SET_INT_SPIN_BOX_PREFIX,
    INTERFACE_GET_INT_SPIN_BOX_PREFIX,
    INTERFACE_SET_INT_SPIN_BOX_SUFFIX,
    INTERFACE_GET_INT_SPIN_BOX_SUFFIX,
    INTERFACE_SET_INT_SPIN_BOX_SINGLE_STEP,
    INTERFACE_GET_INT_SPIN_BOX_SINGLE_STEP,
    INTERFACE_SET_INT_SPIN_BOX_PAGE_STEP,
    INTERFACE_GET_INT_SPIN_BOX_PAGE_STEP,
    INTERFACE_SET_INT_SPIN_BOX_MINIMUM,
    INTERFACE_GET_INT_SPIN_BOX_MINIMUM,
    INTERFACE_SET_INT_SPIN_BOX_MAXIMUM,
    INTERFACE_GET_INT_SPIN_BOX_MAXIMUM,
    INTERFACE_SET_INT_SPIN_BOX_VALUE,
    INTERFACE_GET_INT_SPIN_BOX_VALUE,
    INTERFACE_SET_INT_SPIN_BOX_SPECIAL_VALUE_TEXT,
    INTERFACE_GET_INT_SPIN_BOX_SPECIAL_VALUE_TEXT,

    INTERFACE_NEW_BIN_SPIN_BOX =
    (INTERFACE_BIN_SPIN_BOX_BASE * BASE_SIZE),
    INTERFACE_NEW_BIN_SPIN_BOX_SPACER_0, // spacer
    INTERFACE_NEW_BIN_SPIN_BOX_SPACER_1, // spacer
    INTERFACE_NEW_BIN_SPIN_BOX_SPACER_2, // spacer
    INTERFACE_RESET_BIN_SPIN_BOX,
    INTERFACE_RESET_BIN_SPIN_BOX_SPACER_0, // spacer
    INTERFACE_RESET_BIN_SPIN_BOX_SPACER_1, // spacer
    INTERFACE_RESET_BIN_SPIN_BOX_SPACER_2, // spacer
    INTERFACE_BIN_SPIN_BOX_SIGNAL,
    INTERFACE_BIN_SPIN_BOX_SIGNAL_SPACER_0, // spacer
    INTERFACE_BIN_SPIN_BOX_SIGNAL_SPACER_1, // spacer
    INTERFACE_BIN_SPIN_BOX_SIGNAL_SPACER_2, // spacer
    INTERFACE_SET_BIN_SPIN_BOX_NAME,
    INTERFACE_GET_BIN_SPIN_BOX_NAME,
    INTERFACE_SET_BIN_SPIN_BOX_PREFIX,
    INTERFACE_GET_BIN_SPIN_BOX_PREFIX,
    INTERFACE_SET_BIN_SPIN_BOX_SUFFIX,
    INTERFACE_GET_BIN_SPIN_BOX_SUFFIX,
    INTERFACE_SET_BIN_SPIN_BOX_SINGLE_STEP,
    INTERFACE_GET_BIN_SPIN_BOX_SINGLE_STEP,
    INTERFACE_SET_BIN_SPIN_BOX_PAGE_STEP,
    INTERFACE_GET_BIN_SPIN_BOX_PAGE_STEP,
    INTERFACE_SET_BIN_SPIN_BOX_MINIMUM,
    INTERFACE_GET_BIN_SPIN_BOX_MINIMUM,
    INTERFACE_SET_BIN_SPIN_BOX_MAXIMUM,
    INTERFACE_GET_BIN_SPIN_BOX_MAXIMUM,
    INTERFACE_SET_BIN_SPIN_BOX_VALUE,
    INTERFACE_GET_BIN_SPIN_BOX_VALUE,
    INTERFACE_SET_BIN_SPIN_BOX_SPECIAL_VALUE_TEXT,
    INTERFACE_GET_BIN_SPIN_BOX_SPECIAL_VALUE_TEXT,

    INTERFACE_NEW_HEX_SPIN_BOX =
    (INTERFACE_HEX_SPIN_BOX_BASE * BASE_SIZE),
    INTERFACE_NEW_HEX_SPIN_BOX_SPACER_0, // spacer
    INTERFACE_NEW_HEX_SPIN_BOX_SPACER_1, // spacer
    INTERFACE_NEW_HEX_SPIN_BOX_SPACER_2, // spacer
    INTERFACE_RESET_HEX_SPIN_BOX,
    INTERFACE_RESET_HEX_SPIN_BOX_SPACER_0, // spacer
    INTERFACE_RESET_HEX_SPIN_BOX_SPACER_1, // spacer
    INTERFACE_RESET_HEX_SPIN_BOX_SPACER_2, // spacer
    INTERFACE_HEX_SPIN_BOX_SIGNAL,
    INTERFACE_HEX_SPIN_BOX_SIGNAL_SPACER_0, // spacer
    INTERFACE_HEX_SPIN_BOX_SIGNAL_SPACER_1, // spacer
    INTERFACE_HEX_SPIN_BOX_SIGNAL_SPACER_2, // spacer
    INTERFACE_SET_HEX_SPIN_BOX_NAME,
    INTERFACE_GET_HEX_SPIN_BOX_NAME,
    INTERFACE_SET_HEX_SPIN_BOX_PREFIX,
    INTERFACE_GET_HEX_SPIN_BOX_PREFIX,
    INTERFACE_SET_HEX_SPIN_BOX_SUFFIX,
    INTERFACE_GET_HEX_SPIN_BOX_SUFFIX,
    INTERFACE_SET_HEX_SPIN_BOX_SINGLE_STEP,
    INTERFACE_GET_HEX_SPIN_BOX_SINGLE_STEP,
    INTERFACE_SET_HEX_SPIN_BOX_PAGE_STEP,
    INTERFACE_GET_HEX_SPIN_BOX_PAGE_STEP,
    INTERFACE_SET_HEX_SPIN_BOX_MINIMUM,
    INTERFACE_GET_HEX_SPIN_BOX_MINIMUM,
    INTERFACE_SET_HEX_SPIN_BOX_MAXIMUM,
    INTERFACE_GET_HEX_SPIN_BOX_MAXIMUM,
    INTERFACE_SET_HEX_SPIN_BOX_VALUE,
    INTERFACE_GET_HEX_SPIN_BOX_VALUE,
    INTERFACE_SET_HEX_SPIN_BOX_SPECIAL_VALUE_TEXT,
    INTERFACE_GET_HEX_SPIN_BOX_SPECIAL_VALUE_TEXT,

    INTERFACE_NEW_DOUBLE_SPIN_BOX =
    (INTERFACE_DOUBLE_SPIN_BOX_BASE * BASE_SIZE),
    INTERFACE_NEW_DOUBLE_SPIN_BOX_SPACER_0, // spacer
    INTERFACE_NEW_DOUBLE_SPIN_BOX_SPACER_1, // spacer
    INTERFACE_NEW_DOUBLE_SPIN_BOX_SPACER_2, // spacer
    INTERFACE_RESET_DOUBLE_SPIN_BOX,
    INTERFACE_RESET_DOUBLE_SPIN_BOX_SPACER_0, // spacer
    INTERFACE_RESET_DOUBLE_SPIN_BOX_SPACER_1, // spacer
    INTERFACE_RESET_DOUBLE_SPIN_BOX_SPACER_2, // spacer
    INTERFACE_DOUBLE_SPIN_BOX_SIGNAL,
    INTERFACE_DOUBLE_SPIN_BOX_SIGNAL_SPACER_0, // spacer
    INTERFACE_DOUBLE_SPIN_BOX_SIGNAL_SPACER_1, // spacer
    INTERFACE_DOUBLE_SPIN_BOX_SIGNAL_SPACER_2, // spacer
    INTERFACE_SET_DOUBLE_SPIN_BOX_NAME,
    INTERFACE_GET_DOUBLE_SPIN_BOX_NAME,
    INTERFACE_SET_DOUBLE_SPIN_BOX_PREFIX,
    INTERFACE_GET_DOUBLE_SPIN_BOX_PREFIX,
    INTERFACE_SET_DOUBLE_SPIN_BOX_SUFFIX,
    INTERFACE_GET_DOUBLE_SPIN_BOX_SUFFIX,
    INTERFACE_SET_DOUBLE_SPIN_BOX_SINGLE_STEP,
    INTERFACE_GET_DOUBLE_SPIN_BOX_SINGLE_STEP,
    INTERFACE_SET_DOUBLE_SPIN_BOX_PAGE_STEP,
    INTERFACE_GET_DOUBLE_SPIN_BOX_PAGE_STEP,
    INTERFACE_SET_DOUBLE_SPIN_BOX_MINIMUM,
    INTERFACE_GET_DOUBLE_SPIN_BOX_MINIMUM,
    INTERFACE_SET_DOUBLE_SPIN_BOX_MAXIMUM,
    INTERFACE_GET_DOUBLE_SPIN_BOX_MAXIMUM,
    INTERFACE_SET_DOUBLE_SPIN_BOX_VALUE,
    INTERFACE_GET_DOUBLE_SPIN_BOX_VALUE,
    INTERFACE_SET_DOUBLE_SPIN_BOX_SPECIAL_VALUE_TEXT,
    INTERFACE_GET_DOUBLE_SPIN_BOX_SPECIAL_VALUE_TEXT,

    INTERFACE_NEW_TIME_EDIT =
    (INTERFACE_TIME_EDIT_BASE * BASE_SIZE),
    INTERFACE_NEW_TIME_EDIT_SPACER_0, // spacer
    INTERFACE_NEW_TIME_EDIT_SPACER_1, // spacer
    INTERFACE_NEW_TIME_EDIT_SPACER_2, // spacer
    INTERFACE_RESET_TIME_EDIT,
    INTERFACE_RESET_TIME_EDIT_SPACER_0, // spacer
    INTERFACE_RESET_TIME_EDIT_SPACER_1, // spacer
    INTERFACE_RESET_TIME_EDIT_SPACER_2, // spacer
    INTERFACE_TIME_EDIT_SIGNAL,
    INTERFACE_TIME_EDIT_SIGNAL_SPACER_0, // spacer
    INTERFACE_TIME_EDIT_SIGNAL_SPACER_1, // spacer
    INTERFACE_TIME_EDIT_SIGNAL_SPACER_2, // spacer
    INTERFACE_SET_TIME_EDIT_NAME,
    INTERFACE_GET_TIME_EDIT_NAME,
    INTERFACE_SET_TIME_EDIT_MINIMUM,
    INTERFACE_GET_TIME_EDIT_MINIMUM,
    INTERFACE_SET_TIME_EDIT_MAXIMUM,
    INTERFACE_GET_TIME_EDIT_MAXIMUM,
    INTERFACE_SET_TIME_EDIT_VALUE,
    INTERFACE_GET_TIME_EDIT_VALUE,
    INTERFACE_SET_TIME_EDIT_SPECIAL_VALUE_TEXT,
    INTERFACE_GET_TIME_EDIT_SPECIAL_VALUE_TEXT,

    INTERFACE_NEW_DATE_EDIT =
    (INTERFACE_DATE_EDIT_BASE * BASE_SIZE),
    INTERFACE_NEW_DATE_EDIT_SPACER_0, // spacer
    INTERFACE_NEW_DATE_EDIT_SPACER_1, // spacer
    INTERFACE_NEW_DATE_EDIT_SPACER_2, // spacer
    INTERFACE_RESET_DATE_EDIT,
    INTERFACE_RESET_DATE_EDIT_SPACER_0, // spacer
    INTERFACE_RESET_DATE_EDIT_SPACER_1, // spacer
    INTERFACE_RESET_DATE_EDIT_SPACER_2, // spacer
    INTERFACE_DATE_EDIT_SIGNAL,
    INTERFACE_DATE_EDIT_SIGNAL_SPACER_0, // spacer
    INTERFACE_DATE_EDIT_SIGNAL_SPACER_1, // spacer
    INTERFACE_DATE_EDIT_SIGNAL_SPACER_2, // spacer
    INTERFACE_SET_DATE_EDIT_NAME,
    INTERFACE_GET_DATE_EDIT_NAME,
    INTERFACE_SET_DATE_EDIT_MINIMUM,
    INTERFACE_GET_DATE_EDIT_MINIMUM,
    INTERFACE_SET_DATE_EDIT_MAXIMUM,
    INTERFACE_GET_DATE_EDIT_MAXIMUM,
    INTERFACE_SET_DATE_EDIT_VALUE,
    INTERFACE_GET_DATE_EDIT_VALUE,
    INTERFACE_SET_DATE_EDIT_SPECIAL_VALUE_TEXT,
    INTERFACE_GET_DATE_EDIT_SPECIAL_VALUE_TEXT,

    INTERFACE_NEW_DATE_TIME_EDIT =
    (INTERFACE_DATE_TIME_EDIT_BASE * BASE_SIZE),
    INTERFACE_NEW_DATE_TIME_EDIT_SPACER_0, // spacer
    INTERFACE_NEW_DATE_TIME_EDIT_SPACER_1, // spacer
    INTERFACE_NEW_DATE_TIME_EDIT_SPACER_2, // spacer
    INTERFACE_RESET_DATE_TIME_EDIT,
    INTERFACE_RESET_DATE_TIME_EDIT_SPACER_0, // spacer
    INTERFACE_RESET_DATE_TIME_EDIT_SPACER_1, // spacer
    INTERFACE_RESET_DATE_TIME_EDIT_SPACER_2, // spacer
    INTERFACE_DATE_TIME_EDIT_SIGNAL,
    INTERFACE_DATE_TIME_EDIT_SIGNAL_SPACER_0, // spacer
    INTERFACE_DATE_TIME_EDIT_SIGNAL_SPACER_1, // spacer
    INTERFACE_DATE_TIME_EDIT_SIGNAL_SPACER_2, // spacer
    INTERFACE_SET_DATE_TIME_EDIT_NAME,
    INTERFACE_GET_DATE_TIME_EDIT_NAME,
    INTERFACE_SET_DATE_TIME_EDIT_MINIMUM,
    INTERFACE_GET_DATE_TIME_EDIT_MINIMUM,
    INTERFACE_SET_DATE_TIME_EDIT_MAXIMUM,
    INTERFACE_GET_DATE_TIME_EDIT_MAXIMUM,
    INTERFACE_SET_DATE_TIME_EDIT_VALUE,
    INTERFACE_GET_DATE_TIME_EDIT_VALUE,
    INTERFACE_SET_DATE_TIME_EDIT_SPECIAL_VALUE_TEXT,
    INTERFACE_GET_DATE_TIME_EDIT_SPECIAL_VALUE_TEXT,

    INTERFACE_NEW_SLIDER =
    (INTERFACE_SLIDER_BASE * BASE_SIZE),
    INTERFACE_NEW_SLIDER_SPACER_0, // spacer
    INTERFACE_NEW_SLIDER_SPACER_1, // spacer
    INTERFACE_NEW_SLIDER_SPACER_2, // spacer
    INTERFACE_RESET_SLIDER,
    INTERFACE_RESET_SLIDER_SPACER_0, // spacer
    INTERFACE_RESET_SLIDER_SPACER_1, // spacer
    INTERFACE_RESET_SLIDER_SPACER_2, // spacer
    INTERFACE_SLIDER_SIGNAL,
    INTERFACE_SLIDER_SIGNAL_SPACER_0, // spacer
    INTERFACE_SLIDER_SIGNAL_SPACER_1, // spacer
    INTERFACE_SLIDER_SIGNAL_SPACER_2, // spacer
    INTERFACE_SET_SLIDER_NAME,
    INTERFACE_GET_SLIDER_NAME,
    INTERFACE_SET_SLIDER_SINGLE_STEP,
    INTERFACE_GET_SLIDER_SINGLE_STEP,
    INTERFACE_SET_SLIDER_PAGE_STEP,
    INTERFACE_GET_SLIDER_PAGE_STEP,
    INTERFACE_SET_SLIDER_MINIMUM,
    INTERFACE_GET_SLIDER_MINIMUM,
    INTERFACE_SET_SLIDER_MAXIMUM,
    INTERFACE_GET_SLIDER_MAXIMUM,
    INTERFACE_SET_SLIDER_VALUE,
    INTERFACE_GET_SLIDER_VALUE,

    INTERFACE_NEW_LABEL =
    (INTERFACE_LABEL_BASE * BASE_SIZE),
    INTERFACE_NEW_LABEL_SPACER_0, // spacer
    INTERFACE_NEW_LABEL_SPACER_1, // spacer
    INTERFACE_NEW_LABEL_SPACER_2, // spacer
    INTERFACE_RESET_LABEL_SPACER_0, // spacer
    INTERFACE_RESET_LABEL_SPACER_1, // spacer
    INTERFACE_RESET_LABEL_SPACER_2, // spacer
    INTERFACE_RESET_LABEL_SPACER_3, // spacer
    INTERFACE_LABEL_SIGNAL_SPACER_0, // spacer
    INTERFACE_LABEL_SIGNAL_SPACER_1, // spacer
    INTERFACE_LABEL_SIGNAL_SPACER_2, // spacer
    INTERFACE_LABEL_SIGNAL_SPACER_3, // spacer
    INTERFACE_SET_LABEL_TEXT,
    INTERFACE_GET_LABEL_TEXT,

    INTERFACE_NEW_PROGRESS_BAR =
    (INTERFACE_PROGRESS_BAR_BASE * BASE_SIZE),
    INTERFACE_NEW_PROGRESS_BAR_SPACER_0, // spacer
    INTERFACE_NEW_PROGRESS_BAR_SPACER_1, // spacer
    INTERFACE_NEW_PROGRESS_BAR_SPACER_2, // spacer
    INTERFACE_RESET_PROGRESS_BAR,
    INTERFACE_RESET_PROGRESS_BAR_SPACER_0, // spacer
    INTERFACE_RESET_PROGRESS_BAR_SPACER_1, // spacer
    INTERFACE_RESET_PROGRESS_BAR_SPACER_2, // spacer
    INTERFACE_PROGRESS_BAR_SIGNAL_SPACER_0, // spacer
    INTERFACE_PROGRESS_BAR_SIGNAL_SPACER_1, // spacer
    INTERFACE_PROGRESS_BAR_SIGNAL_SPACER_2, // spacer
    INTERFACE_PROGRESS_BAR_SIGNAL_SPACER_3, // spacer
    INTERFACE_SET_PROGRESS_BAR_NAME,
    INTERFACE_GET_PROGRESS_BAR_NAME,
    INTERFACE_SET_PROGRESS_BAR_MINIMUM,
    INTERFACE_GET_PROGRESS_BAR_MINIMUM,
    INTERFACE_SET_PROGRESS_BAR_MAXIMUM,
    INTERFACE_GET_PROGRESS_BAR_MAXIMUM,
    INTERFACE_SET_PROGRESS_BAR_VALUE,
    INTERFACE_GET_PROGRESS_BAR_VALUE,

    INTERFACE_NEW_SEPERATOR =
    (INTERFACE_SEPERATOR_BASE * BASE_SIZE),
    INTERFACE_NEW_SEPERATOR_SPACER_0, // spacer
    INTERFACE_NEW_SEPERATOR_SPACER_1, // spacer
    INTERFACE_NEW_SEPERATOR_SPACER_2, // spacer
    INTERFACE_RESET_SEPERATOR_SPACER_0, // spacer
    INTERFACE_RESET_SEPERATOR_SPACER_1, // spacer
    INTERFACE_RESET_SEPERATOR_SPACER_2, // spacer
    INTERFACE_RESET_SEPERATOR_SPACER_3, // spacer
    INTERFACE_SEPERATOR_SIGNAL_SPACER_0, // spacer
    INTERFACE_SEPERATOR_SIGNAL_SPACER_1, // spacer
    INTERFACE_SEPERATOR_SIGNAL_SPACER_2, // spacer
    INTERFACE_SEPERATOR_SIGNAL_SPACER_3 // spacer
};

enum DockArea // -> Qt::DockWidgetArea
{
    DA_LEFT = 0x1,
    DA_RIGHT = 0x2,
    DA_TOP = 0x4,
    DA_BOTTOM = 0x8
};

enum CornerArea // -> Qt::Corner
{
    CA_LEFT_MIDDLE,
    CA_LEFT_MIDDLE_TOP,
    CA_LEFT_MIDDLE_BOTTOM,
    CA_LEFT_MIDDLE_TOP_BOTTOM,
    CA_RIGHT_MIDDLE = CA_LEFT_MIDDLE,
    CA_RIGHT_MIDDLE_TOP = CA_LEFT_MIDDLE_TOP,
    CA_RIGHT_MIDDLE_BOTTOM = CA_LEFT_MIDDLE_BOTTOM,
    CA_RIGHT_MIDDLE_TOP_BOTTOM = CA_LEFT_MIDDLE_TOP_BOTTOM,
    CA_TOP_MIDDLE = CA_RIGHT_MIDDLE,
    CA_TOP_MIDDLE_LEFT = CA_RIGHT_MIDDLE_TOP,
    CA_TOP_MIDDLE_RIGHT = CA_RIGHT_MIDDLE_BOTTOM,
    CA_TOP_MIDDLE_LEFT_RIGHT = CA_RIGHT_MIDDLE_TOP_BOTTOM,
    CA_BOTTOM_MIDDLE = CA_TOP_MIDDLE,
    CA_BOTTOM_MIDDLE_LEFT = CA_TOP_MIDDLE_LEFT,
    CA_BOTTOM_MIDDLE_RIGHT = CA_TOP_MIDDLE_RIGHT,
    CA_BOTTOM_MIDDLE_LEFT_RIGHT = CA_TOP_MIDDLE_LEFT_RIGHT
};

enum InputHints // -> Qt::InputMethodHints
{
    IH_NONE = 0x00000000,
    IH_HIDDEN_TEXT = 0x00000001,
    IH_SENSITIVE_DATA = 0x00000002,
    IH_NO_AUTO_UPPERCASE = 0x00000004,
    IH_PREFER_NUMBERS = 0x00000008,
    IH_PREFER_UPPERCASE = 0x00000010,
    IH_PREFER_LOWERCASE = 0x00000020,
    IH_NO_PREDICITVE_TEXT = 0x00000040,
    IH_DATE = 0x00000080,
    IH_TIME = 0x00000100,
    IH_PREFER_LATIN = 0x00000200,
    IH_MULTI_LINE = 0x00000400,
    IH_DIGITS_ONLY = 0x00010000,
    IH_FORMATTED_NUMBERS_ONLY = 0x00020000,
    IH_UPPERCASE_ONLY = 0x00040000,
    IH_LOWERCASE_ONLY = 0x00080000,
    IH_DIALABLE_CHARACTERS_ONLY = 0x00100000,
    IH_EMAIL_CHARACTERS_ONLY = 0x00200000,
    IH_URL_CHARACTERS_ONLY = 0x00400000,
    IH_LATIN_ONLY = 0x00800000,
};

enum StandardButton // -> QMessageBox::StandardButton
{
    SB_OK = 0x00000400,
    SB_YES = 0x00004000,
    SB_NO = 0x00010000,
    SB_CANCEL = 0x00400000
};

enum SerialTerminalControlCharacter
{
    CC_NULL = 0,
    CC_HOME_CURSOR,
    CC_END_CURSOR,
    CC_MOVE_CURSOR_LEFT,
    CC_MOVE_CURSOR_RIGHT,
    CC_MOVE_CURSOR_UP,
    CC_MOVE_CURSOR_DOWN,
    CC_BEEP_SPEAKER,
    CC_BACKSPACE,
    CC_TAB,
    CC_LINE_FEED,
    CC_CLEAR_TO_END_OF_LINE,
    CC_CLEAR_LINES_BELOW,
    CC_CARRIAGE_RETURN,
    CC_CLEAR_TO_START_OF_LINE,
    CC_CLEAR_LINES_ABOVE,
    CC_CLEAR_SCREEN,
    CC_XON,
    CC_SET_FOREGROUND_TO_GRAY,
    CC_XOFF,
    CC_SET_FOREGROUND_TO_BLACK,
    CC_SET_FOREGROUND_TO_BLUE,
    CC_SET_FOREGROUND_TO_RED,
    CC_SET_FOREGROUND_TO_GREEN,
    CC_SET_FOREGROUND_TO_MAGENTA,
    CC_SET_FOREGROUND_TO_CYAN,
    CC_SET_FOREGROUND_TO_YELLOW,
    CC_ESCAPE,
    CC_MOVE_TO_START_OF_LINE,
    CC_MOVE_TO_END_OF_LINE,
    CC_MOVE_TO_PREVIOUS_START_OF_LINE,
    CC_MOVE_TO_NEXT_START_OF_LINE,
    CC_DELETE = 127
};

enum StandardColors // -> Qt::GlobalColor
{
    SC_BLACK = 0xFF000000,
    SC_WHITE = 0xFFFFFFFF,
    SC_DARK_GRAY = 0xFF808080,
    SC_GRAY = 0xFFA0A0A0,
    SC_LIGHT_GRAY = 0xFFC0C0C0,
    SC_RED = 0xFFFF0000,
    SC_GREEN = 0xFF00FF00,
    SC_BLUE = 0xFF0000FF,
    SC_CYAN = 0xFF00FFFF,
    SC_MAGENTA = 0xFFFF00FF,
    SC_YELLOW = 0xFFFFFF00,
    SC_DARK_RED = 0xFF800000,
    SC_DARK_GREEN = 0xFF008000,
    SC_DARK_BLUE = 0xFF000080,
    SC_DARK_CYAN = 0xFF008080,
    SC_DARK_MAGENTA = 0xFF800080,
    SC_DARK_YELLOW = 0xFF808000,
    SC_TRANSPARENT = 0x00000000
};

enum CoordinateSystem
{
    CS_CARTESIAN,
    CS_POLAR
};

enum AngleUnits
{
    AU_DEGREES,
    AU_RADIANS
};

enum LineStyle // -> Qt::PenStyle
{
    LS_NO_PEN,
    LS_SOLID_LINE,
    LS_DASH_LINE,
    LS_DOT_LINE,
    LS_DASH_DOT_LINE,
    LS_DASH_DOT_DOT_LINE
};

enum FillStyle // -> Qt::BrushStyle
{
    FS_NO_BRUSH,
    FS_SOLID_PATTERN,
    FS_DENSE_1_PATTERN, // not supported
    FS_DENSE_2_PATTERN, // not supported
    FS_DENSE_3_PATTERN, // not supported
    FS_DENSE_4_PATTERN, // not supported
    FS_DENSE_5_PATTERN, // not supported
    FS_DENSE_6_PATTERN, // not supported
    FS_DENSE_7_PATTERN, // not supported
    FS_HOR_PATTERN,
    FS_VER_PATTERN,
    FS_CROSS_PATTERN,
    FS_BACKWARD_DIAGONAL_PATTERN,
    FS_FORWARD_DIAGONAL_PATTERN,
    FS_DIAGONAL_PATTERN,
    FS_LINEAR_GRADIENT_PATTERN, // not supported
    FS_RADIAL_GRADIENT_PATTERN, // not supported
    FS_CONICAL_GRADIENT_PATTERN // not supported
};

enum ScaleType // -> QCPAxis::ScaleType
{
    ST_LINEAR,
    ST_LOGARITHMIC
};

enum ScatterShape // -> QCPScatterStyle::ScatterShape
{
    SS_NONE,
    SS_DOT,
    SS_CROSS,
    SS_PLUS,
    SS_CIRCLE,
    SS_DISC,
    SS_SQUARE,
    SS_DIAMOND,
    SS_STAR,
    SS_TRIANGLE,
    SS_TRIANGLE_INVERTED,
    SS_CROSS_SQUARE,
    SS_PLUS_SQUARE,
    SS_CROSS_CIRCLE,
    SS_PLUS_CIRCLE,
    SS_PEACE
};

enum CurveFFT
{
    CFFT_NONE,
    CFFT_FORWARD,
    CFFT_BACKWARD
};

enum CurveFFTWF // FFT Window Function
{
    CFFTWF_RECTANGLE,
    CFFTWF_TRIANGLE,
    CFFTWF_WELCH,
    CFFTWF_HANNING,
    CFFTWF_HAMMING,
    CFFTWF_BLACKMAN,
    CFFTWF_BLACKMAN_HARRIS,
    CFFTWF_BLACKMAN_NUTTAL
};

enum CurveLineStyle // -> QCPCurve::LineStyle
{
    CLS_NONE,
    CLS_LINE
};

enum GraphFFT
{
    GFFT_NONE,
    GFFT_MAGNITUDE,
    GFFT_POWER,
    GFFT_MAGNITUDE_DB,
    GFFT_POWER_DB,
    GFFT_PHASE_RADIANS,
    GFFT_PHASE_DEGREES
};

enum GraphFFTWF // FFT Window Function
{
    GFFTWF_RECTANGLE,
    GFFTWF_TRIANGLE,
    GFFTWF_WELCH,
    GFFTWF_HANNING,
    GFFTWF_HAMMING,
    GFFTWF_BLACKMAN,
    GFFTWF_BLACKMAN_HARRIS,
    GFFTWF_BLACKMAN_NUTTAL
};

enum GraphLineStyle // -> QCPGraph::LineStyle
{
    GLS_NONE,
    GLS_LINE,
    GLS_STEP_LEFT,
    GLS_STEP_RIGHT,
    GLS_STEP_CENTER,
    GLS_IMPULSE
};

enum EchoMode // -> QLineEdit::EchoMode
{
    EM_NORMAL,
    EM_NO_ECHO,
    EM_PASSWORD,
    EM_PASSWORD_ECHO_ON_EDIT
};

enum ButtonSignal
{
    BS_PRESSED,
    BS_RELEASED,
    BS_CLICKED
};

#endif // ILSHARED_H

/***************************************************************************//**
* @file
* @par MIT License - TERMS OF USE:
* @n Permission is hereby granted, free of charge, to any person obtaining a
* copy of this software and associated documentation files (the "Software"), to
* deal in the Software without restriction, including without limitation the
* rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
* sell copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
* @n
* @n The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
* @n
* @n THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
*******************************************************************************/
